// Generated by scripts/generate-examples.mjs; reviewed inputs are beside this file.
import {run} from '../shared.mjs';
export const execute = (client,input) => client.privacy.list(input["trunkId"]);
await run(import.meta.url, 'privacy.list', execute);
