// This file was auto-generated by Fern from our API Definition.

import type * as AgentTrunkApi from "../../../index.js";

export interface DiscoverContextsResponse {
    data: AgentTrunkApi.DiscoveryResult[];
    /** Continue until null, including after empty pages. At most 100 candidates are authorization-checked per request. */
    nextCursor?: (string | null) | undefined;
}
