// This file was auto-generated by Fern from our API Definition.

export interface GetRollbackPlanContextsResponse {
    eligible: boolean;
    expectedStagingRevisionId: string | null;
    reason: string;
}
