// Code generated by Fern. DO NOT EDIT.

package contexts_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	_go "github.com/aadi-labs/agenttrunk-plugins/sdk/go"
	client "github.com/aadi-labs/agenttrunk-plugins/sdk/go/client"
	option "github.com/aadi-labs/agenttrunk-plugins/sdk/go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestContextsExportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.ExportContextsRequest{
		RevisionID: "revisionId",
	}
	_, invocationErr := client.Contexts.Export(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsExportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsExportWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey/export", map[string]interface{}{"revisionId": "revisionId"}, 1)
}

func TestContextsGetRollbackPlanWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.GetRollbackPlanContextsRequest{
		RevisionID: "revisionId",
	}
	_, invocationErr := client.Contexts.GetRollbackPlan(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsGetRollbackPlanWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsGetRollbackPlanWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey/rollback", map[string]interface{}{"revisionId": "revisionId"}, 1)
}

func TestContextsStageRollbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.StageRollbackContextsRequest{
		RevisionID:                "revisionId",
		ExpectedStagingRevisionID: "expectedStagingRevisionId",
		Reason:                    "reason",
	}
	_, invocationErr := client.Contexts.StageRollback(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsStageRollbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsStageRollbackWithWireMock", "POST", "/v1/trunks/trunkId/contexts/contextKey/rollback", nil, 1)
}

func TestContextsPublishWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.PublishInput{
		ContextKey: "contextKey",
		Title:      "title",
		Kind:       _go.ContextKindSkill,
		Files: []*_go.FileInput{
			&_go.FileInput{
				Path:          "path",
				ContentBase64: "contentBase64",
			},
		},
	}
	_, invocationErr := client.Contexts.Publish(
		context.TODO(),
		"trunkId",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsPublishWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsPublishWithWireMock", "POST", "/v1/trunks/trunkId/publications", nil, 1)
}

func TestContextsShareWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	_, invocationErr := client.Contexts.Share(
		context.TODO(),
		"trunkId",
		"contextKey",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsShareWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsShareWithWireMock", "POST", "/v1/trunks/trunkId/contexts/contextKey/share", nil, 1)
}

func TestContextsDiscoverWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.DiscoverContextsRequest{}
	_, invocationErr := client.Contexts.Discover(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsDiscoverWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsDiscoverWithWireMock", "GET", "/v1/contexts", nil, 1)
}

func TestContextsInspectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.InspectContextsRequest{}
	_, invocationErr := client.Contexts.Inspect(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsInspectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsInspectWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey", nil, 1)
}

func TestContextsHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.HistoryContextsRequest{}
	_, invocationErr := client.Contexts.History(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsHistoryWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey/history", nil, 1)
}

func TestContextsCompareWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.CompareContextsRequest{}
	_, invocationErr := client.Contexts.Compare(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsCompareWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsCompareWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey/compare", nil, 1)
}

func TestContextsGetProvenanceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.GetProvenanceContextsRequest{}
	_, invocationErr := client.Contexts.GetProvenance(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsGetProvenanceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsGetProvenanceWithWireMock", "GET", "/v1/trunks/trunkId/contexts/contextKey/provenance", nil, 1)
}

func TestContextsPutProvenanceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.New(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAccessToken("test-token"),
	)
	request := &_go.PutProvenanceContextsRequest{
		RevisionID: "revisionId",
		Text:       "text",
	}
	_, invocationErr := client.Contexts.PutProvenance(
		context.TODO(),
		"trunkId",
		"contextKey",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContextsPutProvenanceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContextsPutProvenanceWithWireMock", "PUT", "/v1/trunks/trunkId/contexts/contextKey/provenance", nil, 1)
}
