// Code generated by Fern. DO NOT EDIT.

package contexts

import (
	context "context"
	io "io"
	os "os"

	_go "github.com/aadi-labs/agenttrunk-plugins/sdk/go"
	core "github.com/aadi-labs/agenttrunk-plugins/sdk/go/core"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	option "github.com/aadi-labs/agenttrunk-plugins/sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AccessToken == "" {
		options.AccessToken = os.Getenv("AGENTTRUNK_ACCESS_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Reads require current context authorization. Includes verified files encoded as base64 and metadata; excludes other history, notes, accounts, logs and backups. Not a complete personal-data export.
//
// Example:
//
//	request := &_go.ExportContextsRequest{
//	    RevisionID: "revisionId",
//	}
//	client.Contexts.Export(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) Export(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.ExportContextsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Export(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Check whether an immutable revision can be restored to staging. This is advisory; the write rechecks permissions, release evidence, and staging concurrency. Ineligible responses do not expose the current staging revision.
//
// Example:
//
//	request := &_go.GetRollbackPlanContextsRequest{
//	    RevisionID: "revisionId",
//	}
//	client.Contexts.GetRollbackPlan(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) GetRollbackPlan(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.GetRollbackPlanContextsRequest,
	opts ...option.RequestOption,
) (*_go.GetRollbackPlanContextsResponse, error) {
	response, err := c.WithRawResponse.GetRollbackPlan(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Restore a previously released immutable revision into staging. Requires production rollback and staging deploy permissions. Production only changes through a subsequent promotion PR.
//
// Example:
//
//	request := &_go.StageRollbackContextsRequest{
//	    RevisionID: "revisionId",
//	    ExpectedStagingRevisionID: "expectedStagingRevisionId",
//	    Reason: "reason",
//	}
//	client.Contexts.StageRollback(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) StageRollback(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.StageRollbackContextsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.StageRollback(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.PublishInput{
//	    ContextKey: "contextKey",
//	    Title: "title",
//	    Kind: _go.ContextKindSkill,
//	    Files: []*_go.FileInput{
//	        &_go.FileInput{
//	            Path: "path",
//	            ContentBase64: "contentBase64",
//	        },
//	    },
//	}
//	client.Contexts.Publish(
//	    context.TODO(),
//	    "trunkId",
//	    request,
//	)
func (c *Client) Publish(
	ctx context.Context,
	trunkID string,
	request *_go.PublishInput,
	opts ...option.RequestOption,
) (*_go.PublishContextsResponse, error) {
	response, err := c.WithRawResponse.Publish(
		ctx,
		trunkID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Contexts.Share(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	)
func (c *Client) Share(
	ctx context.Context,
	trunkID string,
	contextKey string,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Share(
		ctx,
		trunkID,
		contextKey,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.DiscoverContextsRequest{}
//	client.Contexts.Discover(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Discover(
	ctx context.Context,
	request *_go.DiscoverContextsRequest,
	opts ...option.RequestOption,
) (*_go.DiscoverContextsResponse, error) {
	response, err := c.WithRawResponse.Discover(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.InspectContextsRequest{}
//	client.Contexts.Inspect(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) Inspect(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.InspectContextsRequest,
	opts ...option.RequestOption,
) (*_go.InspectContextsResponse, error) {
	response, err := c.WithRawResponse.Inspect(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Atomically add, replace, or delete files in staging, preserving metadata and unchanged files.
// Requires staging read and deployment permission. expectedRevisionId must equal the current
// staging revision. Concurrent branch changes return 409; reread and reconcile, never blindly
// retry. Production is unchanged. The resulting package retains the 256-file, 1 MB per-file,
// and 16 MB total limits and must not be empty. Each path may appear once. Deleting a missing
// file is invalid. Identical content is a no-op; restoring historical content uses rollback.
//
// Example:
//
//	request := &_go.EditContextInput{
//	    ExpectedRevisionID: "expectedRevisionId",
//	    Changes: []*_go.EditContextInputChangesItem{
//	        &_go.EditContextInputChangesItem{
//	            Put: &_go.EditContextInputChangesItemPut{
//	                Path: "path",
//	                ContentBase64: "contentBase64",
//	            },
//	        },
//	    },
//	}
//	client.Contexts.Edit(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) Edit(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.EditContextInput,
	opts ...option.RequestOption,
) (*_go.EditContextsResponse, error) {
	response, err := c.WithRawResponse.Edit(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Follows immutable parent revisions, authorizing every revision. Historic IDs require staging read or shared-context-item read access.
//
// Example:
//
//	request := &_go.HistoryContextsRequest{}
//	client.Contexts.History(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) History(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.HistoryContextsRequest,
	opts ...option.RequestOption,
) (*_go.HistoryContextsResponse, error) {
	response, err := c.WithRawResponse.History(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Authorizes both revisions and returns their manifests, per-file statuses,
// and one selected file preview. Target defaults to latest; base defaults to
// the target's parent, or an empty snapshot for the first revision. The
// returned IDs are immutable; use them for subsequent file selections.
// UTF-8 previews verify file digests and are capped at 128000 bytes per side.
// reason is null, too_large, binary, or too_complex. Omitted previews have
// empty content and zero counts, which must not be displayed as no changes.
//
// Example:
//
//	request := &_go.CompareContextsRequest{}
//	client.Contexts.Compare(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) Compare(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.CompareContextsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Compare(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.GetProvenanceContextsRequest{}
//	client.Contexts.GetProvenance(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) GetProvenance(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.GetProvenanceContextsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.GetProvenance(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires revision read and staging environment deployment permission. Author identity is assigned server-side. Does not modify content, channels, or PR approval. Concurrent updates return 409; reread and reconcile, never blindly retry with a newer token.
//
// Example:
//
//	request := &_go.PutProvenanceContextsRequest{
//	    RevisionID: "revisionId",
//	    Text: "text",
//	}
//	client.Contexts.PutProvenance(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    request,
//	)
func (c *Client) PutProvenance(
	ctx context.Context,
	trunkID string,
	contextKey string,
	request *_go.PutProvenanceContextsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.PutProvenance(
		ctx,
		trunkID,
		contextKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.ReadFileContextsRequest{
//	    Ref: "ref",
//	}
//	client.Contexts.ReadFile(
//	    context.TODO(),
//	    "trunkId",
//	    "contextKey",
//	    "resourcePath",
//	    request,
//	)
func (c *Client) ReadFile(
	ctx context.Context,
	trunkID string,
	contextKey string,
	resourcePath string,
	request *_go.ReadFileContextsRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.ReadFile(
		ctx,
		trunkID,
		contextKey,
		resourcePath,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
