// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateCheckoutBillingRequest(t *testing.T) {
	t.Run("SetPlan", func(t *testing.T) {
		obj := &CreateCheckoutBillingRequest{}
		var fernTestValuePlan CreateCheckoutBillingRequestPlan
		obj.SetPlan(fernTestValuePlan)
		assert.Equal(t, fernTestValuePlan, obj.Plan)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateCheckoutBillingRequest(t *testing.T) {
	t.Run("SetPlan_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingRequest{}
		var fernTestValuePlan CreateCheckoutBillingRequestPlan

		// Act
		obj.SetPlan(fernTestValuePlan)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSetSpendLimitBillingRequest(t *testing.T) {
	t.Run("SetCents", func(t *testing.T) {
		obj := &SetSpendLimitBillingRequest{}
		var fernTestValueCents int
		obj.SetCents(fernTestValueCents)
		assert.Equal(t, fernTestValueCents, obj.Cents)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSetSpendLimitBillingRequest(t *testing.T) {
	t.Run("SetCents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetSpendLimitBillingRequest{}
		var fernTestValueCents int

		// Act
		obj.SetCents(fernTestValueCents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &CreateCheckoutBillingResponse{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}
		var expected string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreatePortalBillingResponse(t *testing.T) {
	t.Run("SetURL", func(t *testing.T) {
		obj := &CreatePortalBillingResponse{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreatePortalBillingResponse(t *testing.T) {
	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}
		var expected string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

}

func TestSettersMarkExplicitCreatePortalBillingResponse(t *testing.T) {
	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetBillingResponse(t *testing.T) {
	t.Run("SetPlan", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValuePlan GetBillingResponsePlan
		obj.SetPlan(fernTestValuePlan)
		assert.Equal(t, fernTestValuePlan, obj.Plan)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccesses", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueAccesses int
		obj.SetAccesses(fernTestValueAccesses)
		assert.Equal(t, fernTestValueAccesses, obj.Accesses)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIncludedAccesses", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueIncludedAccesses *int
		obj.SetIncludedAccesses(fernTestValueIncludedAccesses)
		assert.Equal(t, fernTestValueIncludedAccesses, obj.IncludedAccesses)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSpendLimitCents", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueSpendLimitCents int
		obj.SetSpendLimitCents(fernTestValueSpendLimitCents)
		assert.Equal(t, fernTestValueSpendLimitCents, obj.SpendLimitCents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeteringActive", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueMeteringActive string
		obj.SetMeteringActive(fernTestValueMeteringActive)
		assert.Equal(t, fernTestValueMeteringActive, obj.MeteringActive)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCanManage", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueCanManage bool
		obj.SetCanManage(fernTestValueCanManage)
		assert.Equal(t, fernTestValueCanManage, obj.CanManage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSubscriptionStatus", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueSubscriptionStatus *string
		obj.SetSubscriptionStatus(fernTestValueSubscriptionStatus)
		assert.Equal(t, fernTestValueSubscriptionStatus, obj.SubscriptionStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMonthlyPriceCents", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueMonthlyPriceCents *int
		obj.SetMonthlyPriceCents(fernTestValueMonthlyPriceCents)
		assert.Equal(t, fernTestValueMonthlyPriceCents, obj.MonthlyPriceCents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOverageCents", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueOverageCents *int
		obj.SetOverageCents(fernTestValueOverageCents)
		assert.Equal(t, fernTestValueOverageCents, obj.OverageCents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOverageCentsPerThousand", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueOverageCentsPerThousand *int
		obj.SetOverageCentsPerThousand(fernTestValueOverageCentsPerThousand)
		assert.Equal(t, fernTestValueOverageCentsPerThousand, obj.OverageCentsPerThousand)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPeriod", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValuePeriod *string
		obj.SetPeriod(fernTestValuePeriod)
		assert.Equal(t, fernTestValuePeriod, obj.Period)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHasCustomer", func(t *testing.T) {
		obj := &GetBillingResponse{}
		var fernTestValueHasCustomer *bool
		obj.SetHasCustomer(fernTestValueHasCustomer)
		assert.Equal(t, fernTestValueHasCustomer, obj.HasCustomer)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetBillingResponse(t *testing.T) {
	t.Run("GetPlan", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected GetBillingResponsePlan
		obj.Plan = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlan(), "getter should return the property value")
	})

	t.Run("GetPlan_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlan() // Should return zero value
	})

	t.Run("GetAccesses", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected int
		obj.Accesses = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAccesses(), "getter should return the property value")
	})

	t.Run("GetAccesses_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAccesses() // Should return zero value
	})

	t.Run("GetIncludedAccesses", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *int
		obj.IncludedAccesses = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIncludedAccesses(), "getter should return the property value")
	})

	t.Run("GetIncludedAccesses_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.IncludedAccesses = nil

		// Act & Assert
		assert.Nil(t, obj.GetIncludedAccesses(), "getter should return nil when property is nil")
	})

	t.Run("GetIncludedAccesses_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIncludedAccesses() // Should return zero value
	})

	t.Run("GetSpendLimitCents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected int
		obj.SpendLimitCents = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSpendLimitCents(), "getter should return the property value")
	})

	t.Run("GetSpendLimitCents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSpendLimitCents() // Should return zero value
	})

	t.Run("GetMeteringActive", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected string
		obj.MeteringActive = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeteringActive(), "getter should return the property value")
	})

	t.Run("GetMeteringActive_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeteringActive() // Should return zero value
	})

	t.Run("GetCanManage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected bool
		obj.CanManage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCanManage(), "getter should return the property value")
	})

	t.Run("GetCanManage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCanManage() // Should return zero value
	})

	t.Run("GetSubscriptionStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *string
		obj.SubscriptionStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSubscriptionStatus(), "getter should return the property value")
	})

	t.Run("GetSubscriptionStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.SubscriptionStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetSubscriptionStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetSubscriptionStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSubscriptionStatus() // Should return zero value
	})

	t.Run("GetMonthlyPriceCents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *int
		obj.MonthlyPriceCents = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMonthlyPriceCents(), "getter should return the property value")
	})

	t.Run("GetMonthlyPriceCents_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.MonthlyPriceCents = nil

		// Act & Assert
		assert.Nil(t, obj.GetMonthlyPriceCents(), "getter should return nil when property is nil")
	})

	t.Run("GetMonthlyPriceCents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMonthlyPriceCents() // Should return zero value
	})

	t.Run("GetOverageCents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *int
		obj.OverageCents = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOverageCents(), "getter should return the property value")
	})

	t.Run("GetOverageCents_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.OverageCents = nil

		// Act & Assert
		assert.Nil(t, obj.GetOverageCents(), "getter should return nil when property is nil")
	})

	t.Run("GetOverageCents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOverageCents() // Should return zero value
	})

	t.Run("GetOverageCentsPerThousand", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *int
		obj.OverageCentsPerThousand = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOverageCentsPerThousand(), "getter should return the property value")
	})

	t.Run("GetOverageCentsPerThousand_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.OverageCentsPerThousand = nil

		// Act & Assert
		assert.Nil(t, obj.GetOverageCentsPerThousand(), "getter should return nil when property is nil")
	})

	t.Run("GetOverageCentsPerThousand_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOverageCentsPerThousand() // Should return zero value
	})

	t.Run("GetPeriod", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *string
		obj.Period = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPeriod(), "getter should return the property value")
	})

	t.Run("GetPeriod_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.Period = nil

		// Act & Assert
		assert.Nil(t, obj.GetPeriod(), "getter should return nil when property is nil")
	})

	t.Run("GetPeriod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPeriod() // Should return zero value
	})

	t.Run("GetHasCustomer", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var expected *bool
		obj.HasCustomer = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHasCustomer(), "getter should return the property value")
	})

	t.Run("GetHasCustomer_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		obj.HasCustomer = nil

		// Act & Assert
		assert.Nil(t, obj.GetHasCustomer(), "getter should return nil when property is nil")
	})

	t.Run("GetHasCustomer_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHasCustomer() // Should return zero value
	})

}

func TestSettersMarkExplicitGetBillingResponse(t *testing.T) {
	t.Run("SetPlan_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValuePlan GetBillingResponsePlan

		// Act
		obj.SetPlan(fernTestValuePlan)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccesses_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueAccesses int

		// Act
		obj.SetAccesses(fernTestValueAccesses)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIncludedAccesses_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueIncludedAccesses *int

		// Act
		obj.SetIncludedAccesses(fernTestValueIncludedAccesses)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSpendLimitCents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueSpendLimitCents int

		// Act
		obj.SetSpendLimitCents(fernTestValueSpendLimitCents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeteringActive_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueMeteringActive string

		// Act
		obj.SetMeteringActive(fernTestValueMeteringActive)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCanManage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueCanManage bool

		// Act
		obj.SetCanManage(fernTestValueCanManage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSubscriptionStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueSubscriptionStatus *string

		// Act
		obj.SetSubscriptionStatus(fernTestValueSubscriptionStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMonthlyPriceCents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueMonthlyPriceCents *int

		// Act
		obj.SetMonthlyPriceCents(fernTestValueMonthlyPriceCents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOverageCents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueOverageCents *int

		// Act
		obj.SetOverageCents(fernTestValueOverageCents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOverageCentsPerThousand_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueOverageCentsPerThousand *int

		// Act
		obj.SetOverageCentsPerThousand(fernTestValueOverageCentsPerThousand)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPeriod_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValuePeriod *string

		// Act
		obj.SetPeriod(fernTestValuePeriod)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHasCustomer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}
		var fernTestValueHasCustomer *bool

		// Act
		obj.SetHasCustomer(fernTestValueHasCustomer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("SetSpendLimitCents", func(t *testing.T) {
		obj := &SetSpendLimitBillingResponse{}
		var fernTestValueSpendLimitCents int
		obj.SetSpendLimitCents(fernTestValueSpendLimitCents)
		assert.Equal(t, fernTestValueSpendLimitCents, obj.SpendLimitCents)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("GetSpendLimitCents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetSpendLimitBillingResponse{}
		var expected int
		obj.SpendLimitCents = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSpendLimitCents(), "getter should return the property value")
	})

	t.Run("GetSpendLimitCents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetSpendLimitBillingResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSpendLimitCents() // Should return zero value
	})

}

func TestSettersMarkExplicitSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("SetSpendLimitCents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetSpendLimitBillingResponse{}
		var fernTestValueSpendLimitCents int

		// Act
		obj.SetSpendLimitCents(fernTestValueSpendLimitCents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateCheckoutBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateCheckoutBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateCheckoutBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateCheckoutBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCreatePortalBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePortalBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreatePortalBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreatePortalBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreatePortalBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SetSpendLimitBillingResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SetSpendLimitBillingResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SetSpendLimitBillingResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SetSpendLimitBillingResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateCheckoutBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCreatePortalBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePortalBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SetSpendLimitBillingResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetSpendLimitBillingResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCreateCheckoutBillingRequestPlan(t *testing.T) {
	t.Run("NewFromString_starter", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateCheckoutBillingRequestPlanFromString("starter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateCheckoutBillingRequestPlan("starter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_startup", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateCheckoutBillingRequestPlanFromString("startup")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateCheckoutBillingRequestPlan("startup"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_scale", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateCheckoutBillingRequestPlanFromString("scale")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateCheckoutBillingRequestPlan("scale"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateCheckoutBillingRequestPlanFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateCheckoutBillingRequestPlanFromString("starter")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumGetBillingResponsePlan(t *testing.T) {
	t.Run("NewFromString_free", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetBillingResponsePlanFromString("free")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetBillingResponsePlan("free"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_developer", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetBillingResponsePlanFromString("developer")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetBillingResponsePlan("developer"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_starter", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetBillingResponsePlanFromString("starter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetBillingResponsePlan("starter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_startup", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetBillingResponsePlanFromString("startup")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetBillingResponsePlan("startup"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_scale", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetBillingResponsePlanFromString("scale")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetBillingResponsePlan("scale"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewGetBillingResponsePlanFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewGetBillingResponsePlanFromString("free")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreateCheckoutBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateCheckoutBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateCheckoutBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCreatePortalBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreatePortalBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreatePortalBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSetSpendLimitBillingResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SetSpendLimitBillingResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SetSpendLimitBillingResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
