// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	big "math/big"
	time "time"
)

var (
	compareContextsRequestFieldBase   = big.NewInt(1 << 0)
	compareContextsRequestFieldTarget = big.NewInt(1 << 1)
	compareContextsRequestFieldPath   = big.NewInt(1 << 2)
)

type CompareContextsRequest struct {
	Base   *string `json:"-" url:"base,omitempty"`
	Target *string `json:"-" url:"target,omitempty"`
	Path   *string `json:"-" url:"path,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CompareContextsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBase sets the Base field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompareContextsRequest) SetBase(base *string) {
	c.Base = base
	c.require(compareContextsRequestFieldBase)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompareContextsRequest) SetTarget(target *string) {
	c.Target = target
	c.require(compareContextsRequestFieldTarget)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompareContextsRequest) SetPath(path *string) {
	c.Path = path
	c.require(compareContextsRequestFieldPath)
}

var (
	discoverContextsRequestFieldScopeID = big.NewInt(1 << 0)
	discoverContextsRequestFieldCursor  = big.NewInt(1 << 1)
	discoverContextsRequestFieldTrunkID = big.NewInt(1 << 2)
	discoverContextsRequestFieldQuery   = big.NewInt(1 << 3)
	discoverContextsRequestFieldChannel = big.NewInt(1 << 4)
	discoverContextsRequestFieldLimit   = big.NewInt(1 << 5)
)

type DiscoverContextsRequest struct {
	// Filter by scope before applying the result limit.
	ScopeID *string `json:"-" url:"scopeId,omitempty"`
	// Opaque snapshot continuation returned by the preceding page. Keep filters and principal unchanged; cursors expire after 15 minutes. Authorization is always rechecked. Restart pagination for expired or legacy numeric cursors.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Narrow discovery to this authorized trunk before applying the result limit.
	TrunkID *string                         `json:"-" url:"trunkId,omitempty"`
	Query   *string                         `json:"-" url:"query,omitempty"`
	Channel *DiscoverContextsRequestChannel `json:"-" url:"channel,omitempty"`
	Limit   *int                            `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DiscoverContextsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetScopeID sets the ScopeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetScopeID(scopeID *string) {
	d.ScopeID = scopeID
	d.require(discoverContextsRequestFieldScopeID)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetCursor(cursor *string) {
	d.Cursor = cursor
	d.require(discoverContextsRequestFieldCursor)
}

// SetTrunkID sets the TrunkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetTrunkID(trunkID *string) {
	d.TrunkID = trunkID
	d.require(discoverContextsRequestFieldTrunkID)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetQuery(query *string) {
	d.Query = query
	d.require(discoverContextsRequestFieldQuery)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetChannel(channel *DiscoverContextsRequestChannel) {
	d.Channel = channel
	d.require(discoverContextsRequestFieldChannel)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsRequest) SetLimit(limit *int) {
	d.Limit = limit
	d.require(discoverContextsRequestFieldLimit)
}

var (
	exportContextsRequestFieldRevisionID = big.NewInt(1 << 0)
)

type ExportContextsRequest struct {
	RevisionID string `json:"-" url:"revisionId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *ExportContextsRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExportContextsRequest) SetRevisionID(revisionID string) {
	e.RevisionID = revisionID
	e.require(exportContextsRequestFieldRevisionID)
}

var (
	getProvenanceContextsRequestFieldRef = big.NewInt(1 << 0)
)

type GetProvenanceContextsRequest struct {
	Ref *string `json:"-" url:"ref,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetProvenanceContextsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetProvenanceContextsRequest) SetRef(ref *string) {
	g.Ref = ref
	g.require(getProvenanceContextsRequestFieldRef)
}

var (
	getRollbackPlanContextsRequestFieldRevisionID = big.NewInt(1 << 0)
)

type GetRollbackPlanContextsRequest struct {
	RevisionID string `json:"-" url:"revisionId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetRollbackPlanContextsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRollbackPlanContextsRequest) SetRevisionID(revisionID string) {
	g.RevisionID = revisionID
	g.require(getRollbackPlanContextsRequestFieldRevisionID)
}

var (
	historyContextsRequestFieldFrom  = big.NewInt(1 << 0)
	historyContextsRequestFieldLimit = big.NewInt(1 << 1)
)

type HistoryContextsRequest struct {
	From  *string `json:"-" url:"from,omitempty"`
	Limit *int    `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HistoryContextsRequest) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryContextsRequest) SetFrom(from *string) {
	h.From = from
	h.require(historyContextsRequestFieldFrom)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryContextsRequest) SetLimit(limit *int) {
	h.Limit = limit
	h.require(historyContextsRequestFieldLimit)
}

var (
	inspectContextsRequestFieldRef = big.NewInt(1 << 0)
)

type InspectContextsRequest struct {
	Ref *string `json:"-" url:"ref,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InspectContextsRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InspectContextsRequest) SetRef(ref *string) {
	i.Ref = ref
	i.require(inspectContextsRequestFieldRef)
}

var (
	publishInputFieldContextKey    = big.NewInt(1 << 0)
	publishInputFieldTitle         = big.NewInt(1 << 1)
	publishInputFieldSummary       = big.NewInt(1 << 2)
	publishInputFieldKind          = big.NewInt(1 << 3)
	publishInputFieldTags          = big.NewInt(1 << 4)
	publishInputFieldFiles         = big.NewInt(1 << 5)
	publishInputFieldClaimedDigest = big.NewInt(1 << 6)
	publishInputFieldScopeID       = big.NewInt(1 << 7)
)

type PublishInput struct {
	ContextKey    string       `json:"contextKey" url:"-"`
	Title         string       `json:"title" url:"-"`
	Summary       *string      `json:"summary,omitempty" url:"-"`
	Kind          ContextKind  `json:"kind" url:"-"`
	Tags          []string     `json:"tags,omitempty" url:"-"`
	Files         []*FileInput `json:"files" url:"-"`
	ClaimedDigest *string      `json:"claimedDigest,omitempty" url:"-"`
	ScopeID       *string      `json:"scopeId,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PublishInput) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetContextKey sets the ContextKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetContextKey(contextKey string) {
	p.ContextKey = contextKey
	p.require(publishInputFieldContextKey)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetTitle(title string) {
	p.Title = title
	p.require(publishInputFieldTitle)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetSummary(summary *string) {
	p.Summary = summary
	p.require(publishInputFieldSummary)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetKind(kind ContextKind) {
	p.Kind = kind
	p.require(publishInputFieldKind)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetTags(tags []string) {
	p.Tags = tags
	p.require(publishInputFieldTags)
}

// SetFiles sets the Files field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetFiles(files []*FileInput) {
	p.Files = files
	p.require(publishInputFieldFiles)
}

// SetClaimedDigest sets the ClaimedDigest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetClaimedDigest(claimedDigest *string) {
	p.ClaimedDigest = claimedDigest
	p.require(publishInputFieldClaimedDigest)
}

// SetScopeID sets the ScopeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishInput) SetScopeID(scopeID *string) {
	p.ScopeID = scopeID
	p.require(publishInputFieldScopeID)
}

func (p *PublishInput) UnmarshalJSON(data []byte) error {
	type unmarshaler PublishInput
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PublishInput(body)
	return nil
}

func (p *PublishInput) MarshalJSON() ([]byte, error) {
	type embed PublishInput
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	putProvenanceContextsRequestFieldRevisionID             = big.NewInt(1 << 0)
	putProvenanceContextsRequestFieldText                   = big.NewInt(1 << 1)
	putProvenanceContextsRequestFieldExpectedNotesCommitSha = big.NewInt(1 << 2)
)

type PutProvenanceContextsRequest struct {
	RevisionID string `json:"revisionId" url:"-"`
	// Maximum 16000 UTF-8 bytes; not 16000 arbitrary Unicode characters.
	Text string `json:"text" url:"-"`
	// Null for the first note; otherwise the notesCommitSha returned by GET.
	ExpectedNotesCommitSha *string `json:"expectedNotesCommitSha,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PutProvenanceContextsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutProvenanceContextsRequest) SetRevisionID(revisionID string) {
	p.RevisionID = revisionID
	p.require(putProvenanceContextsRequestFieldRevisionID)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutProvenanceContextsRequest) SetText(text string) {
	p.Text = text
	p.require(putProvenanceContextsRequestFieldText)
}

// SetExpectedNotesCommitSha sets the ExpectedNotesCommitSha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutProvenanceContextsRequest) SetExpectedNotesCommitSha(expectedNotesCommitSha *string) {
	p.ExpectedNotesCommitSha = expectedNotesCommitSha
	p.require(putProvenanceContextsRequestFieldExpectedNotesCommitSha)
}

func (p *PutProvenanceContextsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PutProvenanceContextsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PutProvenanceContextsRequest(body)
	return nil
}

func (p *PutProvenanceContextsRequest) MarshalJSON() ([]byte, error) {
	type embed PutProvenanceContextsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	readFileContextsRequestFieldRef = big.NewInt(1 << 0)
)

type ReadFileContextsRequest struct {
	// Immutable revision ID from inspect; resolve moving channels before reading.
	Ref string `json:"-" url:"ref"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReadFileContextsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadFileContextsRequest) SetRef(ref string) {
	r.Ref = ref
	r.require(readFileContextsRequestFieldRef)
}

var (
	stageRollbackContextsRequestFieldRevisionID                = big.NewInt(1 << 0)
	stageRollbackContextsRequestFieldExpectedStagingRevisionID = big.NewInt(1 << 1)
	stageRollbackContextsRequestFieldReason                    = big.NewInt(1 << 2)
)

type StageRollbackContextsRequest struct {
	RevisionID                string `json:"revisionId" url:"-"`
	ExpectedStagingRevisionID string `json:"expectedStagingRevisionId" url:"-"`
	Reason                    string `json:"reason" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StageRollbackContextsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StageRollbackContextsRequest) SetRevisionID(revisionID string) {
	s.RevisionID = revisionID
	s.require(stageRollbackContextsRequestFieldRevisionID)
}

// SetExpectedStagingRevisionID sets the ExpectedStagingRevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StageRollbackContextsRequest) SetExpectedStagingRevisionID(expectedStagingRevisionID string) {
	s.ExpectedStagingRevisionID = expectedStagingRevisionID
	s.require(stageRollbackContextsRequestFieldExpectedStagingRevisionID)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StageRollbackContextsRequest) SetReason(reason string) {
	s.Reason = reason
	s.require(stageRollbackContextsRequestFieldReason)
}

func (s *StageRollbackContextsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler StageRollbackContextsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = StageRollbackContextsRequest(body)
	return nil
}

func (s *StageRollbackContextsRequest) MarshalJSON() ([]byte, error) {
	type embed StageRollbackContextsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	contextFieldID        = big.NewInt(1 << 0)
	contextFieldTrunkID   = big.NewInt(1 << 1)
	contextFieldScopeID   = big.NewInt(1 << 2)
	contextFieldKey       = big.NewInt(1 << 3)
	contextFieldTitle     = big.NewInt(1 << 4)
	contextFieldKind      = big.NewInt(1 << 5)
	contextFieldSummary   = big.NewInt(1 << 6)
	contextFieldTags      = big.NewInt(1 << 7)
	contextFieldCreatedAt = big.NewInt(1 << 8)
	contextFieldUpdatedAt = big.NewInt(1 << 9)
)

type Context struct {
	ID        string      `json:"id" url:"id"`
	TrunkID   string      `json:"trunkId" url:"trunkId"`
	ScopeID   string      `json:"scopeId" url:"scopeId"`
	Key       string      `json:"key" url:"key"`
	Title     string      `json:"title" url:"title"`
	Kind      ContextKind `json:"kind" url:"kind"`
	Summary   string      `json:"summary" url:"summary"`
	Tags      []string    `json:"tags" url:"tags"`
	CreatedAt time.Time   `json:"createdAt" url:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Context) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Context) GetTrunkID() string {
	if c == nil {
		return ""
	}
	return c.TrunkID
}

func (c *Context) GetScopeID() string {
	if c == nil {
		return ""
	}
	return c.ScopeID
}

func (c *Context) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *Context) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}

func (c *Context) GetKind() ContextKind {
	if c == nil {
		return ""
	}
	return c.Kind
}

func (c *Context) GetSummary() string {
	if c == nil {
		return ""
	}
	return c.Summary
}

func (c *Context) GetTags() []string {
	if c == nil {
		return nil
	}
	return c.Tags
}

func (c *Context) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Context) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Context) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Context) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetID(id string) {
	c.ID = id
	c.require(contextFieldID)
}

// SetTrunkID sets the TrunkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetTrunkID(trunkID string) {
	c.TrunkID = trunkID
	c.require(contextFieldTrunkID)
}

// SetScopeID sets the ScopeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetScopeID(scopeID string) {
	c.ScopeID = scopeID
	c.require(contextFieldScopeID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetKey(key string) {
	c.Key = key
	c.require(contextFieldKey)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetTitle(title string) {
	c.Title = title
	c.require(contextFieldTitle)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetKind(kind ContextKind) {
	c.Kind = kind
	c.require(contextFieldKind)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetSummary(summary string) {
	c.Summary = summary
	c.require(contextFieldSummary)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetTags(tags []string) {
	c.Tags = tags
	c.require(contextFieldTags)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(contextFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Context) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(contextFieldUpdatedAt)
}

func (c *Context) UnmarshalJSON(data []byte) error {
	type embed Context
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = Context(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Context) MarshalJSON() ([]byte, error) {
	type embed Context
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Context) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ContextKind string

const (
	ContextKindSkill        ContextKind = "skill"
	ContextKindDocs         ContextKind = "docs"
	ContextKindPrompt       ContextKind = "prompt"
	ContextKindPolicy       ContextKind = "policy"
	ContextKindMemorySchema ContextKind = "memory-schema"
)

func NewContextKindFromString(s string) (ContextKind, error) {
	switch s {
	case "skill":
		return ContextKindSkill, nil
	case "docs":
		return ContextKindDocs, nil
	case "prompt":
		return ContextKindPrompt, nil
	case "policy":
		return ContextKindPolicy, nil
	case "memory-schema":
		return ContextKindMemorySchema, nil
	}
	var t ContextKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ContextKind) Ptr() *ContextKind {
	return &c
}

var (
	discoveryResultFieldTrunkID       = big.NewInt(1 << 0)
	discoveryResultFieldScopeID       = big.NewInt(1 << 1)
	discoveryResultFieldContextKey    = big.NewInt(1 << 2)
	discoveryResultFieldTitle         = big.NewInt(1 << 3)
	discoveryResultFieldKind          = big.NewInt(1 << 4)
	discoveryResultFieldSummary       = big.NewInt(1 << 5)
	discoveryResultFieldTags          = big.NewInt(1 << 6)
	discoveryResultFieldRevisionID    = big.NewInt(1 << 7)
	discoveryResultFieldPackageDigest = big.NewInt(1 << 8)
	discoveryResultFieldChannel       = big.NewInt(1 << 9)
	discoveryResultFieldUpdatedAt     = big.NewInt(1 << 10)
)

type DiscoveryResult struct {
	TrunkID       string                 `json:"trunkId" url:"trunkId"`
	ScopeID       string                 `json:"scopeId" url:"scopeId"`
	ContextKey    string                 `json:"contextKey" url:"contextKey"`
	Title         string                 `json:"title" url:"title"`
	Kind          ContextKind            `json:"kind" url:"kind"`
	Summary       string                 `json:"summary" url:"summary"`
	Tags          []string               `json:"tags" url:"tags"`
	RevisionID    string                 `json:"revisionId" url:"revisionId"`
	PackageDigest string                 `json:"packageDigest" url:"packageDigest"`
	Channel       DiscoveryResultChannel `json:"channel" url:"channel"`
	UpdatedAt     time.Time              `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DiscoveryResult) GetTrunkID() string {
	if d == nil {
		return ""
	}
	return d.TrunkID
}

func (d *DiscoveryResult) GetScopeID() string {
	if d == nil {
		return ""
	}
	return d.ScopeID
}

func (d *DiscoveryResult) GetContextKey() string {
	if d == nil {
		return ""
	}
	return d.ContextKey
}

func (d *DiscoveryResult) GetTitle() string {
	if d == nil {
		return ""
	}
	return d.Title
}

func (d *DiscoveryResult) GetKind() ContextKind {
	if d == nil {
		return ""
	}
	return d.Kind
}

func (d *DiscoveryResult) GetSummary() string {
	if d == nil {
		return ""
	}
	return d.Summary
}

func (d *DiscoveryResult) GetTags() []string {
	if d == nil {
		return nil
	}
	return d.Tags
}

func (d *DiscoveryResult) GetRevisionID() string {
	if d == nil {
		return ""
	}
	return d.RevisionID
}

func (d *DiscoveryResult) GetPackageDigest() string {
	if d == nil {
		return ""
	}
	return d.PackageDigest
}

func (d *DiscoveryResult) GetChannel() DiscoveryResultChannel {
	if d == nil {
		return ""
	}
	return d.Channel
}

func (d *DiscoveryResult) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *DiscoveryResult) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DiscoveryResult) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetTrunkID sets the TrunkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetTrunkID(trunkID string) {
	d.TrunkID = trunkID
	d.require(discoveryResultFieldTrunkID)
}

// SetScopeID sets the ScopeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetScopeID(scopeID string) {
	d.ScopeID = scopeID
	d.require(discoveryResultFieldScopeID)
}

// SetContextKey sets the ContextKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetContextKey(contextKey string) {
	d.ContextKey = contextKey
	d.require(discoveryResultFieldContextKey)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetTitle(title string) {
	d.Title = title
	d.require(discoveryResultFieldTitle)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetKind(kind ContextKind) {
	d.Kind = kind
	d.require(discoveryResultFieldKind)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetSummary(summary string) {
	d.Summary = summary
	d.require(discoveryResultFieldSummary)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetTags(tags []string) {
	d.Tags = tags
	d.require(discoveryResultFieldTags)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetRevisionID(revisionID string) {
	d.RevisionID = revisionID
	d.require(discoveryResultFieldRevisionID)
}

// SetPackageDigest sets the PackageDigest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetPackageDigest(packageDigest string) {
	d.PackageDigest = packageDigest
	d.require(discoveryResultFieldPackageDigest)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetChannel(channel DiscoveryResultChannel) {
	d.Channel = channel
	d.require(discoveryResultFieldChannel)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoveryResult) SetUpdatedAt(updatedAt time.Time) {
	d.UpdatedAt = updatedAt
	d.require(discoveryResultFieldUpdatedAt)
}

func (d *DiscoveryResult) UnmarshalJSON(data []byte) error {
	type embed DiscoveryResult
	var unmarshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DiscoveryResult(unmarshaler.embed)
	d.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DiscoveryResult) MarshalJSON() ([]byte, error) {
	type embed DiscoveryResult
	var marshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*d),
		UpdatedAt: internal.NewDateTime(d.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DiscoveryResult) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DiscoveryResultChannel string

const (
	DiscoveryResultChannelProduction DiscoveryResultChannel = "production"
	DiscoveryResultChannelStaging    DiscoveryResultChannel = "staging"
	DiscoveryResultChannelLatest     DiscoveryResultChannel = "latest"
)

func NewDiscoveryResultChannelFromString(s string) (DiscoveryResultChannel, error) {
	switch s {
	case "production":
		return DiscoveryResultChannelProduction, nil
	case "staging":
		return DiscoveryResultChannelStaging, nil
	case "latest":
		return DiscoveryResultChannelLatest, nil
	}
	var t DiscoveryResultChannel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DiscoveryResultChannel) Ptr() *DiscoveryResultChannel {
	return &d
}

var (
	fileInputFieldPath          = big.NewInt(1 << 0)
	fileInputFieldContentBase64 = big.NewInt(1 << 1)
)

type FileInput struct {
	Path          string `json:"path" url:"path"`
	ContentBase64 string `json:"contentBase64" url:"contentBase64"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FileInput) GetPath() string {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FileInput) GetContentBase64() string {
	if f == nil {
		return ""
	}
	return f.ContentBase64
}

func (f *FileInput) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FileInput) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileInput) SetPath(path string) {
	f.Path = path
	f.require(fileInputFieldPath)
}

// SetContentBase64 sets the ContentBase64 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileInput) SetContentBase64(contentBase64 string) {
	f.ContentBase64 = contentBase64
	f.require(fileInputFieldContentBase64)
}

func (f *FileInput) UnmarshalJSON(data []byte) error {
	type unmarshaler FileInput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FileInput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FileInput) MarshalJSON() ([]byte, error) {
	type embed FileInput
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FileInput) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fileRecordFieldPath   = big.NewInt(1 << 0)
	fileRecordFieldSize   = big.NewInt(1 << 1)
	fileRecordFieldSha256 = big.NewInt(1 << 2)
)

type FileRecord struct {
	Path   string `json:"path" url:"path"`
	Size   int    `json:"size" url:"size"`
	Sha256 string `json:"sha256" url:"sha256"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FileRecord) GetPath() string {
	if f == nil {
		return ""
	}
	return f.Path
}

func (f *FileRecord) GetSize() int {
	if f == nil {
		return 0
	}
	return f.Size
}

func (f *FileRecord) GetSha256() string {
	if f == nil {
		return ""
	}
	return f.Sha256
}

func (f *FileRecord) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FileRecord) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileRecord) SetPath(path string) {
	f.Path = path
	f.require(fileRecordFieldPath)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileRecord) SetSize(size int) {
	f.Size = size
	f.require(fileRecordFieldSize)
}

// SetSha256 sets the Sha256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileRecord) SetSha256(sha256 string) {
	f.Sha256 = sha256
	f.require(fileRecordFieldSha256)
}

func (f *FileRecord) UnmarshalJSON(data []byte) error {
	type unmarshaler FileRecord
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FileRecord(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FileRecord) MarshalJSON() ([]byte, error) {
	type embed FileRecord
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FileRecord) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	revisionFieldID               = big.NewInt(1 << 0)
	revisionFieldContextID        = big.NewInt(1 << 1)
	revisionFieldPackageDigest    = big.NewInt(1 << 2)
	revisionFieldParentRevisionID = big.NewInt(1 << 3)
	revisionFieldFiles            = big.NewInt(1 << 4)
	revisionFieldCreatedAt        = big.NewInt(1 << 5)
)

type Revision struct {
	ID               string        `json:"id" url:"id"`
	ContextID        string        `json:"contextId" url:"contextId"`
	PackageDigest    string        `json:"packageDigest" url:"packageDigest"`
	ParentRevisionID *string       `json:"parentRevisionId,omitempty" url:"parentRevisionId,omitempty"`
	Files            []*FileRecord `json:"files" url:"files"`
	CreatedAt        time.Time     `json:"createdAt" url:"createdAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *Revision) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Revision) GetContextID() string {
	if r == nil {
		return ""
	}
	return r.ContextID
}

func (r *Revision) GetPackageDigest() string {
	if r == nil {
		return ""
	}
	return r.PackageDigest
}

func (r *Revision) GetParentRevisionID() *string {
	if r == nil {
		return nil
	}
	return r.ParentRevisionID
}

func (r *Revision) GetFiles() []*FileRecord {
	if r == nil {
		return nil
	}
	return r.Files
}

func (r *Revision) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Revision) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *Revision) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetID(id string) {
	r.ID = id
	r.require(revisionFieldID)
}

// SetContextID sets the ContextID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetContextID(contextID string) {
	r.ContextID = contextID
	r.require(revisionFieldContextID)
}

// SetPackageDigest sets the PackageDigest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetPackageDigest(packageDigest string) {
	r.PackageDigest = packageDigest
	r.require(revisionFieldPackageDigest)
}

// SetParentRevisionID sets the ParentRevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetParentRevisionID(parentRevisionID *string) {
	r.ParentRevisionID = parentRevisionID
	r.require(revisionFieldParentRevisionID)
}

// SetFiles sets the Files field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetFiles(files []*FileRecord) {
	r.Files = files
	r.require(revisionFieldFiles)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *Revision) SetCreatedAt(createdAt time.Time) {
	r.CreatedAt = createdAt
	r.require(revisionFieldCreatedAt)
}

func (r *Revision) UnmarshalJSON(data []byte) error {
	type embed Revision
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = Revision(unmarshaler.embed)
	r.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *Revision) MarshalJSON() ([]byte, error) {
	type embed Revision
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*r),
		CreatedAt: internal.NewDateTime(r.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *Revision) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type DiscoverContextsRequestChannel string

const (
	DiscoverContextsRequestChannelProduction DiscoverContextsRequestChannel = "production"
	DiscoverContextsRequestChannelStaging    DiscoverContextsRequestChannel = "staging"
	DiscoverContextsRequestChannelLatest     DiscoverContextsRequestChannel = "latest"
)

func NewDiscoverContextsRequestChannelFromString(s string) (DiscoverContextsRequestChannel, error) {
	switch s {
	case "production":
		return DiscoverContextsRequestChannelProduction, nil
	case "staging":
		return DiscoverContextsRequestChannelStaging, nil
	case "latest":
		return DiscoverContextsRequestChannelLatest, nil
	}
	var t DiscoverContextsRequestChannel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DiscoverContextsRequestChannel) Ptr() *DiscoverContextsRequestChannel {
	return &d
}

var (
	discoverContextsResponseFieldData       = big.NewInt(1 << 0)
	discoverContextsResponseFieldNextCursor = big.NewInt(1 << 1)
)

type DiscoverContextsResponse struct {
	Data []*DiscoveryResult `json:"data" url:"data"`
	// Continue until null, including after empty pages. At most 100 candidates are authorization-checked per request.
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DiscoverContextsResponse) GetData() []*DiscoveryResult {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DiscoverContextsResponse) GetNextCursor() *string {
	if d == nil {
		return nil
	}
	return d.NextCursor
}

func (d *DiscoverContextsResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DiscoverContextsResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsResponse) SetData(data []*DiscoveryResult) {
	d.Data = data
	d.require(discoverContextsResponseFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverContextsResponse) SetNextCursor(nextCursor *string) {
	d.NextCursor = nextCursor
	d.require(discoverContextsResponseFieldNextCursor)
}

func (d *DiscoverContextsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DiscoverContextsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DiscoverContextsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DiscoverContextsResponse) MarshalJSON() ([]byte, error) {
	type embed DiscoverContextsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DiscoverContextsResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getRollbackPlanContextsResponseFieldEligible                  = big.NewInt(1 << 0)
	getRollbackPlanContextsResponseFieldExpectedStagingRevisionID = big.NewInt(1 << 1)
	getRollbackPlanContextsResponseFieldReason                    = big.NewInt(1 << 2)
)

type GetRollbackPlanContextsResponse struct {
	Eligible                  bool    `json:"eligible" url:"eligible"`
	ExpectedStagingRevisionID *string `json:"expectedStagingRevisionId,omitempty" url:"expectedStagingRevisionId,omitempty"`
	Reason                    string  `json:"reason" url:"reason"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetRollbackPlanContextsResponse) GetEligible() bool {
	if g == nil {
		return false
	}
	return g.Eligible
}

func (g *GetRollbackPlanContextsResponse) GetExpectedStagingRevisionID() *string {
	if g == nil {
		return nil
	}
	return g.ExpectedStagingRevisionID
}

func (g *GetRollbackPlanContextsResponse) GetReason() string {
	if g == nil {
		return ""
	}
	return g.Reason
}

func (g *GetRollbackPlanContextsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetRollbackPlanContextsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetEligible sets the Eligible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRollbackPlanContextsResponse) SetEligible(eligible bool) {
	g.Eligible = eligible
	g.require(getRollbackPlanContextsResponseFieldEligible)
}

// SetExpectedStagingRevisionID sets the ExpectedStagingRevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRollbackPlanContextsResponse) SetExpectedStagingRevisionID(expectedStagingRevisionID *string) {
	g.ExpectedStagingRevisionID = expectedStagingRevisionID
	g.require(getRollbackPlanContextsResponseFieldExpectedStagingRevisionID)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRollbackPlanContextsResponse) SetReason(reason string) {
	g.Reason = reason
	g.require(getRollbackPlanContextsResponseFieldReason)
}

func (g *GetRollbackPlanContextsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetRollbackPlanContextsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetRollbackPlanContextsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetRollbackPlanContextsResponse) MarshalJSON() ([]byte, error) {
	type embed GetRollbackPlanContextsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetRollbackPlanContextsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	historyContextsResponseFieldData = big.NewInt(1 << 0)
	historyContextsResponseFieldNext = big.NewInt(1 << 1)
)

type HistoryContextsResponse struct {
	Data []*Revision `json:"data" url:"data"`
	Next *string     `json:"next,omitempty" url:"next,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HistoryContextsResponse) GetData() []*Revision {
	if h == nil {
		return nil
	}
	return h.Data
}

func (h *HistoryContextsResponse) GetNext() *string {
	if h == nil {
		return nil
	}
	return h.Next
}

func (h *HistoryContextsResponse) GetExtraProperties() map[string]interface{} {
	if h == nil {
		return nil
	}
	return h.extraProperties
}

func (h *HistoryContextsResponse) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryContextsResponse) SetData(data []*Revision) {
	h.Data = data
	h.require(historyContextsResponseFieldData)
}

// SetNext sets the Next field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryContextsResponse) SetNext(next *string) {
	h.Next = next
	h.require(historyContextsResponseFieldNext)
}

func (h *HistoryContextsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler HistoryContextsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HistoryContextsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HistoryContextsResponse) MarshalJSON() ([]byte, error) {
	type embed HistoryContextsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HistoryContextsResponse) String() string {
	if h == nil {
		return "<nil>"
	}
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

var (
	inspectContextsResponseFieldContext  = big.NewInt(1 << 0)
	inspectContextsResponseFieldRevision = big.NewInt(1 << 1)
)

type InspectContextsResponse struct {
	Context  *Context  `json:"context" url:"context"`
	Revision *Revision `json:"revision" url:"revision"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InspectContextsResponse) GetContext() *Context {
	if i == nil {
		return nil
	}
	return i.Context
}

func (i *InspectContextsResponse) GetRevision() *Revision {
	if i == nil {
		return nil
	}
	return i.Revision
}

func (i *InspectContextsResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InspectContextsResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetContext sets the Context field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InspectContextsResponse) SetContext(context *Context) {
	i.Context = context
	i.require(inspectContextsResponseFieldContext)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InspectContextsResponse) SetRevision(revision *Revision) {
	i.Revision = revision
	i.require(inspectContextsResponseFieldRevision)
}

func (i *InspectContextsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InspectContextsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InspectContextsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InspectContextsResponse) MarshalJSON() ([]byte, error) {
	type embed InspectContextsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InspectContextsResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	publishContextsResponseFieldContext  = big.NewInt(1 << 0)
	publishContextsResponseFieldRevision = big.NewInt(1 << 1)
)

type PublishContextsResponse struct {
	Context  *Context  `json:"context" url:"context"`
	Revision *Revision `json:"revision" url:"revision"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PublishContextsResponse) GetContext() *Context {
	if p == nil {
		return nil
	}
	return p.Context
}

func (p *PublishContextsResponse) GetRevision() *Revision {
	if p == nil {
		return nil
	}
	return p.Revision
}

func (p *PublishContextsResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PublishContextsResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetContext sets the Context field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishContextsResponse) SetContext(context *Context) {
	p.Context = context
	p.require(publishContextsResponseFieldContext)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PublishContextsResponse) SetRevision(revision *Revision) {
	p.Revision = revision
	p.require(publishContextsResponseFieldRevision)
}

func (p *PublishContextsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PublishContextsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PublishContextsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PublishContextsResponse) MarshalJSON() ([]byte, error) {
	type embed PublishContextsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PublishContextsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
