// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	big "math/big"
)

var (
	createContextSetsRequestFieldName    = big.NewInt(1 << 0)
	createContextSetsRequestFieldSources = big.NewInt(1 << 1)
)

type CreateContextSetsRequest struct {
	Name    string              `json:"name" url:"-"`
	Sources []*ContextSetSource `json:"sources" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateContextSetsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContextSetsRequest) SetName(name string) {
	c.Name = name
	c.require(createContextSetsRequestFieldName)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateContextSetsRequest) SetSources(sources []*ContextSetSource) {
	c.Sources = sources
	c.require(createContextSetsRequestFieldSources)
}

func (c *CreateContextSetsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateContextSetsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateContextSetsRequest(body)
	return nil
}

func (c *CreateContextSetsRequest) MarshalJSON() ([]byte, error) {
	type embed CreateContextSetsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listContextSetsRequestFieldCursor = big.NewInt(1 << 0)
	listContextSetsRequestFieldLimit  = big.NewInt(1 << 1)
)

type ListContextSetsRequest struct {
	Cursor *string `json:"-" url:"cursor,omitempty"`
	Limit  *int    `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListContextSetsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextSetsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listContextSetsRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextSetsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listContextSetsRequestFieldLimit)
}

var (
	sourcesContextSetsRequestFieldCursor = big.NewInt(1 << 0)
)

type SourcesContextSetsRequest struct {
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SourcesContextSetsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourcesContextSetsRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(sourcesContextSetsRequestFieldCursor)
}

var (
	contextSetSourceFieldSourceTrunkID = big.NewInt(1 << 0)
	contextSetSourceFieldSourceScopeID = big.NewInt(1 << 1)
	contextSetSourceFieldEnvironmentID = big.NewInt(1 << 2)
	contextSetSourceFieldContextKey    = big.NewInt(1 << 3)
	contextSetSourceFieldRevisionID    = big.NewInt(1 << 4)
	contextSetSourceFieldPackageDigest = big.NewInt(1 << 5)
	contextSetSourceFieldMountPath     = big.NewInt(1 << 6)
	contextSetSourceFieldRequired      = big.NewInt(1 << 7)
)

type ContextSetSource struct {
	SourceTrunkID string `json:"sourceTrunkId" url:"sourceTrunkId"`
	SourceScopeID string `json:"sourceScopeId" url:"sourceScopeId"`
	EnvironmentID string `json:"environmentId" url:"environmentId"`
	ContextKey    string `json:"contextKey" url:"contextKey"`
	RevisionID    string `json:"revisionId" url:"revisionId"`
	PackageDigest string `json:"packageDigest" url:"packageDigest"`
	MountPath     string `json:"mountPath" url:"mountPath"`
	Required      bool   `json:"required" url:"required"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContextSetSource) GetSourceTrunkID() string {
	if c == nil {
		return ""
	}
	return c.SourceTrunkID
}

func (c *ContextSetSource) GetSourceScopeID() string {
	if c == nil {
		return ""
	}
	return c.SourceScopeID
}

func (c *ContextSetSource) GetEnvironmentID() string {
	if c == nil {
		return ""
	}
	return c.EnvironmentID
}

func (c *ContextSetSource) GetContextKey() string {
	if c == nil {
		return ""
	}
	return c.ContextKey
}

func (c *ContextSetSource) GetRevisionID() string {
	if c == nil {
		return ""
	}
	return c.RevisionID
}

func (c *ContextSetSource) GetPackageDigest() string {
	if c == nil {
		return ""
	}
	return c.PackageDigest
}

func (c *ContextSetSource) GetMountPath() string {
	if c == nil {
		return ""
	}
	return c.MountPath
}

func (c *ContextSetSource) GetRequired() bool {
	if c == nil {
		return false
	}
	return c.Required
}

func (c *ContextSetSource) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ContextSetSource) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSourceTrunkID sets the SourceTrunkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetSourceTrunkID(sourceTrunkID string) {
	c.SourceTrunkID = sourceTrunkID
	c.require(contextSetSourceFieldSourceTrunkID)
}

// SetSourceScopeID sets the SourceScopeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetSourceScopeID(sourceScopeID string) {
	c.SourceScopeID = sourceScopeID
	c.require(contextSetSourceFieldSourceScopeID)
}

// SetEnvironmentID sets the EnvironmentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetEnvironmentID(environmentID string) {
	c.EnvironmentID = environmentID
	c.require(contextSetSourceFieldEnvironmentID)
}

// SetContextKey sets the ContextKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetContextKey(contextKey string) {
	c.ContextKey = contextKey
	c.require(contextSetSourceFieldContextKey)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetRevisionID(revisionID string) {
	c.RevisionID = revisionID
	c.require(contextSetSourceFieldRevisionID)
}

// SetPackageDigest sets the PackageDigest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetPackageDigest(packageDigest string) {
	c.PackageDigest = packageDigest
	c.require(contextSetSourceFieldPackageDigest)
}

// SetMountPath sets the MountPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetMountPath(mountPath string) {
	c.MountPath = mountPath
	c.require(contextSetSourceFieldMountPath)
}

// SetRequired sets the Required field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContextSetSource) SetRequired(required bool) {
	c.Required = required
	c.require(contextSetSourceFieldRequired)
}

func (c *ContextSetSource) UnmarshalJSON(data []byte) error {
	type unmarshaler ContextSetSource
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ContextSetSource(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContextSetSource) MarshalJSON() ([]byte, error) {
	type embed ContextSetSource
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ContextSetSource) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
