// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	big "math/big"
	time "time"
)

var (
	createScopesRequestFieldName = big.NewInt(1 << 0)
	createScopesRequestFieldSlug = big.NewInt(1 << 1)
)

type CreateScopesRequest struct {
	Name string  `json:"name" url:"-"`
	Slug *string `json:"slug,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateScopesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateScopesRequest) SetName(name string) {
	c.Name = name
	c.require(createScopesRequestFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateScopesRequest) SetSlug(slug *string) {
	c.Slug = slug
	c.require(createScopesRequestFieldSlug)
}

func (c *CreateScopesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateScopesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateScopesRequest(body)
	return nil
}

func (c *CreateScopesRequest) MarshalJSON() ([]byte, error) {
	type embed CreateScopesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	scopeFieldCanCreateScope = big.NewInt(1 << 0)
	scopeFieldID             = big.NewInt(1 << 1)
	scopeFieldName           = big.NewInt(1 << 2)
	scopeFieldSlug           = big.NewInt(1 << 3)
	scopeFieldCreatedBy      = big.NewInt(1 << 4)
	scopeFieldCreatedAt      = big.NewInt(1 << 5)
	scopeFieldEnvironments   = big.NewInt(1 << 6)
)

type Scope struct {
	CanCreateScope *bool                    `json:"canCreateScope,omitempty" url:"canCreateScope,omitempty"`
	ID             string                   `json:"id" url:"id"`
	Name           string                   `json:"name" url:"name"`
	Slug           string                   `json:"slug" url:"slug"`
	CreatedBy      string                   `json:"createdBy" url:"createdBy"`
	CreatedAt      time.Time                `json:"createdAt" url:"createdAt"`
	Environments   []*ScopeEnvironmentsItem `json:"environments" url:"environments"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Scope) GetCanCreateScope() *bool {
	if s == nil {
		return nil
	}
	return s.CanCreateScope
}

func (s *Scope) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Scope) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Scope) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *Scope) GetCreatedBy() string {
	if s == nil {
		return ""
	}
	return s.CreatedBy
}

func (s *Scope) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Scope) GetEnvironments() []*ScopeEnvironmentsItem {
	if s == nil {
		return nil
	}
	return s.Environments
}

func (s *Scope) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *Scope) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCanCreateScope sets the CanCreateScope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetCanCreateScope(canCreateScope *bool) {
	s.CanCreateScope = canCreateScope
	s.require(scopeFieldCanCreateScope)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetID(id string) {
	s.ID = id
	s.require(scopeFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetName(name string) {
	s.Name = name
	s.require(scopeFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetSlug(slug string) {
	s.Slug = slug
	s.require(scopeFieldSlug)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetCreatedBy(createdBy string) {
	s.CreatedBy = createdBy
	s.require(scopeFieldCreatedBy)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetCreatedAt(createdAt time.Time) {
	s.CreatedAt = createdAt
	s.require(scopeFieldCreatedAt)
}

// SetEnvironments sets the Environments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Scope) SetEnvironments(environments []*ScopeEnvironmentsItem) {
	s.Environments = environments
	s.require(scopeFieldEnvironments)
}

func (s *Scope) UnmarshalJSON(data []byte) error {
	type embed Scope
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = Scope(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Scope) MarshalJSON() ([]byte, error) {
	type embed Scope
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewDateTime(s.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Scope) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	scopeEnvironmentsItemFieldID         = big.NewInt(1 << 0)
	scopeEnvironmentsItemFieldName       = big.NewInt(1 << 1)
	scopeEnvironmentsItemFieldCommitSha  = big.NewInt(1 << 2)
	scopeEnvironmentsItemFieldCanDeploy  = big.NewInt(1 << 3)
	scopeEnvironmentsItemFieldCanPropose = big.NewInt(1 << 4)
	scopeEnvironmentsItemFieldCanPublish = big.NewInt(1 << 5)
)

type ScopeEnvironmentsItem struct {
	ID         string                    `json:"id" url:"id"`
	Name       ScopeEnvironmentsItemName `json:"name" url:"name"`
	CommitSha  *string                   `json:"commitSha,omitempty" url:"commitSha,omitempty"`
	CanDeploy  *bool                     `json:"canDeploy,omitempty" url:"canDeploy,omitempty"`
	CanPropose *bool                     `json:"canPropose,omitempty" url:"canPropose,omitempty"`
	CanPublish *bool                     `json:"canPublish,omitempty" url:"canPublish,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ScopeEnvironmentsItem) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ScopeEnvironmentsItem) GetName() ScopeEnvironmentsItemName {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *ScopeEnvironmentsItem) GetCommitSha() *string {
	if s == nil {
		return nil
	}
	return s.CommitSha
}

func (s *ScopeEnvironmentsItem) GetCanDeploy() *bool {
	if s == nil {
		return nil
	}
	return s.CanDeploy
}

func (s *ScopeEnvironmentsItem) GetCanPropose() *bool {
	if s == nil {
		return nil
	}
	return s.CanPropose
}

func (s *ScopeEnvironmentsItem) GetCanPublish() *bool {
	if s == nil {
		return nil
	}
	return s.CanPublish
}

func (s *ScopeEnvironmentsItem) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *ScopeEnvironmentsItem) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetID(id string) {
	s.ID = id
	s.require(scopeEnvironmentsItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetName(name ScopeEnvironmentsItemName) {
	s.Name = name
	s.require(scopeEnvironmentsItemFieldName)
}

// SetCommitSha sets the CommitSha field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetCommitSha(commitSha *string) {
	s.CommitSha = commitSha
	s.require(scopeEnvironmentsItemFieldCommitSha)
}

// SetCanDeploy sets the CanDeploy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetCanDeploy(canDeploy *bool) {
	s.CanDeploy = canDeploy
	s.require(scopeEnvironmentsItemFieldCanDeploy)
}

// SetCanPropose sets the CanPropose field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetCanPropose(canPropose *bool) {
	s.CanPropose = canPropose
	s.require(scopeEnvironmentsItemFieldCanPropose)
}

// SetCanPublish sets the CanPublish field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *ScopeEnvironmentsItem) SetCanPublish(canPublish *bool) {
	s.CanPublish = canPublish
	s.require(scopeEnvironmentsItemFieldCanPublish)
}

func (s *ScopeEnvironmentsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ScopeEnvironmentsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ScopeEnvironmentsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ScopeEnvironmentsItem) MarshalJSON() ([]byte, error) {
	type embed ScopeEnvironmentsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *ScopeEnvironmentsItem) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type ScopeEnvironmentsItemName string

const (
	ScopeEnvironmentsItemNameStaging    ScopeEnvironmentsItemName = "staging"
	ScopeEnvironmentsItemNameProduction ScopeEnvironmentsItemName = "production"
)

func NewScopeEnvironmentsItemNameFromString(s string) (ScopeEnvironmentsItemName, error) {
	switch s {
	case "staging":
		return ScopeEnvironmentsItemNameStaging, nil
	case "production":
		return ScopeEnvironmentsItemNameProduction, nil
	}
	var t ScopeEnvironmentsItemName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ScopeEnvironmentsItemName) Ptr() *ScopeEnvironmentsItemName {
	return &s
}

var (
	listScopesResponseFieldData = big.NewInt(1 << 0)
)

type ListScopesResponse struct {
	Data []*Scope `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListScopesResponse) GetData() []*Scope {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListScopesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListScopesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListScopesResponse) SetData(data []*Scope) {
	l.Data = data
	l.require(listScopesResponseFieldData)
}

func (l *ListScopesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListScopesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListScopesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListScopesResponse) MarshalJSON() ([]byte, error) {
	type embed ListScopesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListScopesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
