// Generated by scripts/generate-examples.mjs; reviewed inputs are beside this file.
import {run} from '../shared.mjs';
export const execute = (client,input) => client.billing.get();
await run(import.meta.url, 'billing.get', execute);
