// Generated by scripts/generate-examples.mjs; reviewed inputs are beside this file.
import {run} from '../shared.mjs';
export const execute = (client,input) => client.workspaces.audit(input["trunkId"], input["request"]);
await run(import.meta.url, 'workspaces.audit', execute);
