// This file was auto-generated by Fern from our API Definition.

import type * as AgentTrunkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         expectedRevisionId: "expectedRevisionId",
 *         changes: [{
 *                 operation: "put",
 *                 path: "path",
 *                 contentBase64: "contentBase64"
 *             }]
 *     }
 */
export interface EditContextInput {
    expectedRevisionId: string;
    changes: AgentTrunkApi.EditContextInputChangesItem[];
}
