// Code generated by Fern. DO NOT EDIT.

package contextsets

import (
	context "context"
	os "os"

	_go "github.com/aadi-labs/agenttrunk-plugins/sdk/go"
	core "github.com/aadi-labs/agenttrunk-plugins/sdk/go/core"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	option "github.com/aadi-labs/agenttrunk-plugins/sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AccessToken == "" {
		options.AccessToken = os.Getenv("AGENTTRUNK_ACCESS_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns up to 20 candidates with current authorization checks and an opaque nextCursor. Snapshots expire after 15 minutes; narrow the scope if the 10000-record or 8 MB snapshot limit is exceeded.
//
// Example:
//
//	request := &_go.SourcesContextSetsRequest{}
//	client.ContextSets.Sources(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Sources(
	ctx context.Context,
	request *_go.SourcesContextSetsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Sources(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Snapshot-stable candidates with current WorkOS authorization rechecked on each page. Cursors expire after 15 minutes and are bound to the principal and filters.
//
// Example:
//
//	request := &_go.ListContextSetsRequest{}
//	client.ContextSets.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *_go.ListContextSetsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.CreateContextSetsRequest{
//	    Name: "name",
//	    Sources: []*_go.ContextSetSource{
//	        &_go.ContextSetSource{
//	            SourceTrunkID: "sourceTrunkId",
//	            SourceScopeID: "sourceScopeId",
//	            EnvironmentID: "environmentId",
//	            ContextKey: "contextKey",
//	            RevisionID: "revisionId",
//	            PackageDigest: "packageDigest",
//	            MountPath: "mountPath",
//	            Required: true,
//	        },
//	    },
//	}
//	client.ContextSets.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *_go.CreateContextSetsRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.ContextSets.Resolve(
//	    context.TODO(),
//	    "contextSetId",
//	)
func (c *Client) Resolve(
	ctx context.Context,
	contextSetID string,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Resolve(
		ctx,
		contextSetID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
