// This file was auto-generated by Fern from our API Definition.

import type * as AgentTrunkApi from "../index.js";

export interface DiscoveryResult {
    trunkId: string;
    scopeId: string;
    contextKey: string;
    title: string;
    kind: AgentTrunkApi.ContextKind;
    summary: string;
    tags: string[];
    revisionId: string;
    packageDigest: string;
    channel: DiscoveryResult.Channel;
    updatedAt: string;
}

export namespace DiscoveryResult {
    export const Channel = {
        Production: "production",
        Staging: "staging",
        Latest: "latest",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
