// This file was auto-generated by Fern from our API Definition.

export interface Trunk {
    id: string;
    organizationId: string;
    name: string;
    slug: string;
    createdBy: string;
    branches: Trunk.Branches;
    createdAt: string;
}

export namespace Trunk {
    export interface Branches {
        staging: string | null;
        production: string | null;
    }
}
