// Code generated by Fern. DO NOT EDIT.

package workspaces

import (
	context "context"
	os "os"

	_go "github.com/aadi-labs/agenttrunk-plugins/sdk/go"
	core "github.com/aadi-labs/agenttrunk-plugins/sdk/go/core"
	internal "github.com/aadi-labs/agenttrunk-plugins/sdk/go/internal"
	option "github.com/aadi-labs/agenttrunk-plugins/sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AccessToken == "" {
		options.AccessToken = os.Getenv("AGENTTRUNK_ACCESS_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &_go.ListWorkspacesRequest{}
//	client.Workspaces.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *_go.ListWorkspacesRequest,
	opts ...option.RequestOption,
) (*_go.ListWorkspacesResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.CreateTrunkInput{
//	    Name: "name",
//	}
//	client.Workspaces.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *_go.CreateTrunkInput,
	opts ...option.RequestOption,
) (*_go.Trunk, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Workspaces.Get(
//	    context.TODO(),
//	    "trunkId",
//	)
func (c *Client) Get(
	ctx context.Context,
	trunkID string,
	opts ...option.RequestOption,
) (*_go.Trunk, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		trunkID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.AuditWorkspacesRequest{}
//	client.Workspaces.Audit(
//	    context.TODO(),
//	    "trunkId",
//	    request,
//	)
func (c *Client) Audit(
	ctx context.Context,
	trunkID string,
	request *_go.AuditWorkspacesRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Audit(
		ctx,
		trunkID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
