# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_checkout_billing_request_plan import CreateCheckoutBillingRequestPlan
    from .create_checkout_billing_response import CreateCheckoutBillingResponse
    from .create_portal_billing_response import CreatePortalBillingResponse
    from .get_billing_response import GetBillingResponse
    from .get_billing_response_plan import GetBillingResponsePlan
    from .set_spend_limit_billing_response import SetSpendLimitBillingResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateCheckoutBillingRequestPlan": ".create_checkout_billing_request_plan",
    "CreateCheckoutBillingResponse": ".create_checkout_billing_response",
    "CreatePortalBillingResponse": ".create_portal_billing_response",
    "GetBillingResponse": ".get_billing_response",
    "GetBillingResponsePlan": ".get_billing_response_plan",
    "SetSpendLimitBillingResponse": ".set_spend_limit_billing_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateCheckoutBillingRequestPlan",
    "CreateCheckoutBillingResponse",
    "CreatePortalBillingResponse",
    "GetBillingResponse",
    "GetBillingResponsePlan",
    "SetSpendLimitBillingResponse",
]
