// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AgentTrunkApi from "../../../index.js";

export declare namespace ContextsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ContextsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ContextsClient.Options>;

    constructor(options: ContextsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Reads require current context authorization. Includes verified files encoded as base64 and metadata; excludes other history, notes, accounts, logs and backups. Not a complete personal-data export.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.ExportContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.export("trunkId", "contextKey", {
     *         revisionId: "revisionId"
     *     })
     */
    public export(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.ExportContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__export(trunkId, contextKey, request, requestOptions));
    }

    private async __export(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.ExportContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { revisionId } = request;
        const _queryParams: Record<string, unknown> = {
            revisionId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/export`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/export",
        );
    }

    /**
     * Check whether an immutable revision can be restored to staging. This is advisory; the write rechecks permissions, release evidence, and staging concurrency. Ineligible responses do not expose the current staging revision.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.GetRollbackPlanContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.ForbiddenError}
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.getRollbackPlan("trunkId", "contextKey", {
     *         revisionId: "revisionId"
     *     })
     */
    public getRollbackPlan(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.GetRollbackPlanContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<AgentTrunkApi.GetRollbackPlanContextsResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getRollbackPlan(trunkId, contextKey, request, requestOptions),
        );
    }

    private async __getRollbackPlan(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.GetRollbackPlanContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AgentTrunkApi.GetRollbackPlanContextsResponse>> {
        const { revisionId } = request;
        const _queryParams: Record<string, unknown> = {
            revisionId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/rollback`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AgentTrunkApi.GetRollbackPlanContextsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new AgentTrunkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/rollback",
        );
    }

    /**
     * Restore a previously released immutable revision into staging. Requires production rollback and staging deploy permissions. Production only changes through a subsequent promotion PR.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.StageRollbackContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.ForbiddenError}
     * @throws {@link AgentTrunkApi.ConflictError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.stageRollback("trunkId", "contextKey", {
     *         revisionId: "revisionId",
     *         expectedStagingRevisionId: "expectedStagingRevisionId",
     *         reason: "reason"
     *     })
     */
    public stageRollback(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.StageRollbackContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__stageRollback(trunkId, contextKey, request, requestOptions));
    }

    private async __stageRollback(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.StageRollbackContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/rollback`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new AgentTrunkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new AgentTrunkApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/rollback",
        );
    }

    /**
     * @param {string} trunkId
     * @param {AgentTrunkApi.PublishInput} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.ContentTooLargeError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.publish("trunkId", {
     *         contextKey: "contextKey",
     *         title: "title",
     *         kind: "skill",
     *         files: [{
     *                 path: "path",
     *                 contentBase64: "contentBase64"
     *             }]
     *     })
     */
    public publish(
        trunkId: string,
        request: AgentTrunkApi.PublishInput,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<AgentTrunkApi.PublishContextsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__publish(trunkId, request, requestOptions));
    }

    private async __publish(
        trunkId: string,
        request: AgentTrunkApi.PublishInput,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AgentTrunkApi.PublishContextsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/publications`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AgentTrunkApi.PublishContextsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 413:
                    throw new AgentTrunkApi.ContentTooLargeError(
                        _response.error.body as AgentTrunkApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/trunks/{trunkId}/publications",
        );
    }

    /**
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.share("trunkId", "contextKey")
     */
    public share(
        trunkId: string,
        contextKey: string,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__share(trunkId, contextKey, requestOptions));
    }

    private async __share(
        trunkId: string,
        contextKey: string,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/share`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgentTrunkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/share",
        );
    }

    /**
     * @param {AgentTrunkApi.DiscoverContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.discover()
     */
    public discover(
        request: AgentTrunkApi.DiscoverContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<AgentTrunkApi.DiscoverContextsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__discover(request, requestOptions));
    }

    private async __discover(
        request: AgentTrunkApi.DiscoverContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AgentTrunkApi.DiscoverContextsResponse>> {
        const { scopeId, cursor, trunkId, query, channel, limit } = request;
        const _queryParams: Record<string, unknown> = {
            scopeId,
            cursor,
            trunkId,
            query,
            channel: channel != null ? channel : undefined,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                "v1/contexts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AgentTrunkApi.DiscoverContextsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgentTrunkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/contexts");
    }

    /**
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.InspectContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.inspect("trunkId", "contextKey")
     */
    public inspect(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.InspectContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<AgentTrunkApi.InspectContextsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__inspect(trunkId, contextKey, request, requestOptions));
    }

    private async __inspect(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.InspectContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AgentTrunkApi.InspectContextsResponse>> {
        const { ref } = request;
        const _queryParams: Record<string, unknown> = {
            ref,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AgentTrunkApi.InspectContextsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}",
        );
    }

    /**
     * Follows immutable parent revisions, authorizing every revision. Historic IDs require staging read or shared-context-item read access.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.HistoryContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.history("trunkId", "contextKey")
     */
    public history(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.HistoryContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<AgentTrunkApi.HistoryContextsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__history(trunkId, contextKey, request, requestOptions));
    }

    private async __history(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.HistoryContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AgentTrunkApi.HistoryContextsResponse>> {
        const { from: from_, limit } = request;
        const _queryParams: Record<string, unknown> = {
            from: from_,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/history`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AgentTrunkApi.HistoryContextsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/history",
        );
    }

    /**
     * Authorizes both revisions and returns their manifests, per-file statuses,
     * and one selected file preview. Target defaults to latest; base defaults to
     * the target's parent, or an empty snapshot for the first revision. The
     * returned IDs are immutable; use them for subsequent file selections.
     * UTF-8 previews verify file digests and are capped at 128000 bytes per side.
     * reason is null, too_large, binary, or too_complex. Omitted previews have
     * empty content and zero counts, which must not be displayed as no changes.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.CompareContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.compare("trunkId", "contextKey")
     */
    public compare(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.CompareContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__compare(trunkId, contextKey, request, requestOptions));
    }

    private async __compare(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.CompareContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { base, target, path } = request;
        const _queryParams: Record<string, unknown> = {
            base,
            target,
            path,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/compare`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/compare",
        );
    }

    /**
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.GetProvenanceContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.getProvenance("trunkId", "contextKey")
     */
    public getProvenance(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.GetProvenanceContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getProvenance(trunkId, contextKey, request, requestOptions));
    }

    private async __getProvenance(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.GetProvenanceContextsRequest = {},
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { ref } = request;
        const _queryParams: Record<string, unknown> = {
            ref,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/provenance`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/provenance",
        );
    }

    /**
     * Requires revision read and staging environment deployment permission. Author identity is assigned server-side. Does not modify content, channels, or PR approval. Concurrent updates return 409; reread and reconcile, never blindly retry with a newer token.
     *
     * @param {string} trunkId
     * @param {string} contextKey
     * @param {AgentTrunkApi.PutProvenanceContextsRequest} request
     * @param {ContextsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AgentTrunkApi.BadRequestError}
     * @throws {@link AgentTrunkApi.ForbiddenError}
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link AgentTrunkApi.ConflictError}
     * @throws {@link AgentTrunkApi.BadGatewayError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     *
     * @example
     *     await client.contexts.putProvenance("trunkId", "contextKey", {
     *         revisionId: "revisionId",
     *         text: "text"
     *     })
     */
    public putProvenance(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.PutProvenanceContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__putProvenance(trunkId, contextKey, request, requestOptions));
    }

    private async __putProvenance(
        trunkId: string,
        contextKey: string,
        request: AgentTrunkApi.PutProvenanceContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/provenance`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AgentTrunkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new AgentTrunkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new AgentTrunkApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new AgentTrunkApi.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/provenance",
        );
    }

    /**
     * @throws {@link AgentTrunkApi.NotFoundError}
     * @throws {@link errors.AgentTrunkApiError}
     * @throws {@link errors.AgentTrunkTimeoutError}
     */
    public readFile(
        trunkId: string,
        contextKey: string,
        resourcePath: string,
        request: AgentTrunkApi.ReadFileContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__readFile(trunkId, contextKey, resourcePath, request, requestOptions),
        );
    }

    private async __readFile(
        trunkId: string,
        contextKey: string,
        resourcePath: string,
        request: AgentTrunkApi.ReadFileContextsRequest,
        requestOptions?: ContextsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { ref } = request;
        const _queryParams: Record<string, unknown> = {
            ref,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgentTrunkEnvironment.Default,
                `v1/trunks/${core.url.encodePathParam(trunkId)}/contexts/${core.url.encodePathParam(contextKey)}/files/${core.url.encodePathParam(resourcePath)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AgentTrunkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AgentTrunkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/trunks/{trunkId}/contexts/{contextKey}/files/{resourcePath}",
        );
    }
}
