// This file was auto-generated by Fern from our API Definition.

export const AgentTrunkEnvironment = {
    Default: "https://api.agenttrunk.ai",
} as const;

export type AgentTrunkEnvironment = typeof AgentTrunkEnvironment.Default;
