# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient
from .types.create_portal_webhooks_response import CreatePortalWebhooksResponse
from .types.list_webhooks_response import ListWebhooksResponse


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list(
        self,
        trunk_id: str,
        *,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        Requires trunk management permission. Lists at most 50 workspace submission receipts, not endpoint delivery receipts. Pass nextCursor as before until null.

        Parameters
        ----------
        trunk_id : str

        before : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Workspace-scoped submission page.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.webhooks.list(
            trunk_id="trunkId",
        )
        """
        _response = self._raw_client.list(trunk_id, before=before, request_options=request_options)
        return _response.data

    def create_portal(
        self, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalWebhooksResponse:
        """
        Requires trunk management permission. Enables future workspace events and returns a one-hour bearer access URL for endpoint configuration, delivery inspection, and replay. Never cache or log the URL. Previously issued links remain valid until expiry.

        Parameters
        ----------
        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalWebhooksResponse
            No-store response containing a private portal URL.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.webhooks.create_portal(
            trunk_id="trunkId",
        )
        """
        _response = self._raw_client.create_portal(trunk_id, request_options=request_options)
        return _response.data

    def retry(
        self, trunk_id: str, event_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Requires trunk management permission. Requeue a failed provider submission with the same event identity. Accepted messages must be replayed through the Svix portal. Consumers must deduplicate events.

        Parameters
        ----------
        trunk_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Failed submission queued for retry.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.webhooks.retry(
            trunk_id="trunkId",
            event_id="eventId",
        )
        """
        _response = self._raw_client.retry(trunk_id, event_id, request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list(
        self,
        trunk_id: str,
        *,
        before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        Requires trunk management permission. Lists at most 50 workspace submission receipts, not endpoint delivery receipts. Pass nextCursor as before until null.

        Parameters
        ----------
        trunk_id : str

        before : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Workspace-scoped submission page.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.list(
                trunk_id="trunkId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(trunk_id, before=before, request_options=request_options)
        return _response.data

    async def create_portal(
        self, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalWebhooksResponse:
        """
        Requires trunk management permission. Enables future workspace events and returns a one-hour bearer access URL for endpoint configuration, delivery inspection, and replay. Never cache or log the URL. Previously issued links remain valid until expiry.

        Parameters
        ----------
        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalWebhooksResponse
            No-store response containing a private portal URL.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.create_portal(
                trunk_id="trunkId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_portal(trunk_id, request_options=request_options)
        return _response.data

    async def retry(
        self, trunk_id: str, event_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Requires trunk management permission. Requeue a failed provider submission with the same event identity. Accepted messages must be replayed through the Svix portal. Consumers must deduplicate events.

        Parameters
        ----------
        trunk_id : str

        event_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Failed submission queued for retry.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.webhooks.retry(
                trunk_id="trunkId",
                event_id="eventId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retry(trunk_id, event_id, request_options=request_options)
        return _response.data
