# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Context,
        ContextKind,
        ContextSetSource,
        DiscoveryResult,
        DiscoveryResultChannel,
        Error,
        ErrorError,
        FileInput,
        FileRecord,
        PromotionRequest,
        PromotionRequestChangesItem,
        PromotionRequestStatus,
        Revision,
        Scope,
        ScopeEnvironmentsItem,
        ScopeEnvironmentsItemName,
        Trunk,
        TrunkBranches,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ConflictError,
        ContentTooLargeError,
        ForbiddenError,
        NotFoundError,
        ServiceUnavailableError,
    )
    from . import billing, context_sets, contexts, health, privacy, releases, scopes, webhooks, workspaces
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .billing import (
        CreateCheckoutBillingRequestPlan,
        CreateCheckoutBillingResponse,
        CreatePortalBillingResponse,
        GetBillingResponse,
        GetBillingResponsePlan,
        SetSpendLimitBillingResponse,
    )
    from .client import AgentTrunk, AsyncAgentTrunk
    from .contexts import (
        DiscoverContextsRequestChannel,
        DiscoverContextsResponse,
        EditContextInputChangesItem,
        EditContextInputChangesItemDelete,
        EditContextInputChangesItemPut,
        EditContextInputChangesItem_Delete,
        EditContextInputChangesItem_Put,
        EditContextsResponse,
        GetRollbackPlanContextsResponse,
        HistoryContextsResponse,
        InspectContextsResponse,
        PublishContextsResponse,
    )
    from .environment import AgentTrunkEnvironment
    from .privacy import CreatePrivacyRequestKind
    from .releases import ListReleasesRequestStatus, ListReleasesResponse
    from .scopes import ListScopesResponse
    from .version import __version__
    from .webhooks import (
        CreatePortalWebhooksResponse,
        ListWebhooksResponse,
        ListWebhooksResponseDataItem,
        ListWebhooksResponseDataItemStatus,
    )
    from .workspaces import CreateTrunkInputBaseline, ListWorkspacesResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AgentTrunk": ".client",
    "AgentTrunkEnvironment": ".environment",
    "AsyncAgentTrunk": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "ConflictError": ".errors",
    "ContentTooLargeError": ".errors",
    "Context": ".types",
    "ContextKind": ".types",
    "ContextSetSource": ".types",
    "CreateCheckoutBillingRequestPlan": ".billing",
    "CreateCheckoutBillingResponse": ".billing",
    "CreatePortalBillingResponse": ".billing",
    "CreatePortalWebhooksResponse": ".webhooks",
    "CreatePrivacyRequestKind": ".privacy",
    "CreateTrunkInputBaseline": ".workspaces",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "DiscoverContextsRequestChannel": ".contexts",
    "DiscoverContextsResponse": ".contexts",
    "DiscoveryResult": ".types",
    "DiscoveryResultChannel": ".types",
    "EditContextInputChangesItem": ".contexts",
    "EditContextInputChangesItemDelete": ".contexts",
    "EditContextInputChangesItemPut": ".contexts",
    "EditContextInputChangesItem_Delete": ".contexts",
    "EditContextInputChangesItem_Put": ".contexts",
    "EditContextsResponse": ".contexts",
    "Error": ".types",
    "ErrorError": ".types",
    "FileInput": ".types",
    "FileRecord": ".types",
    "ForbiddenError": ".errors",
    "GetBillingResponse": ".billing",
    "GetBillingResponsePlan": ".billing",
    "GetRollbackPlanContextsResponse": ".contexts",
    "HistoryContextsResponse": ".contexts",
    "InspectContextsResponse": ".contexts",
    "ListReleasesRequestStatus": ".releases",
    "ListReleasesResponse": ".releases",
    "ListScopesResponse": ".scopes",
    "ListWebhooksResponse": ".webhooks",
    "ListWebhooksResponseDataItem": ".webhooks",
    "ListWebhooksResponseDataItemStatus": ".webhooks",
    "ListWorkspacesResponse": ".workspaces",
    "NotFoundError": ".errors",
    "PromotionRequest": ".types",
    "PromotionRequestChangesItem": ".types",
    "PromotionRequestStatus": ".types",
    "PublishContextsResponse": ".contexts",
    "Revision": ".types",
    "Scope": ".types",
    "ScopeEnvironmentsItem": ".types",
    "ScopeEnvironmentsItemName": ".types",
    "ServiceUnavailableError": ".errors",
    "SetSpendLimitBillingResponse": ".billing",
    "Trunk": ".types",
    "TrunkBranches": ".types",
    "__version__": ".version",
    "billing": ".billing",
    "context_sets": ".context_sets",
    "contexts": ".contexts",
    "health": ".health",
    "privacy": ".privacy",
    "releases": ".releases",
    "scopes": ".scopes",
    "webhooks": ".webhooks",
    "workspaces": ".workspaces",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentTrunk",
    "AgentTrunkEnvironment",
    "AsyncAgentTrunk",
    "BadGatewayError",
    "BadRequestError",
    "ConflictError",
    "ContentTooLargeError",
    "Context",
    "ContextKind",
    "ContextSetSource",
    "CreateCheckoutBillingRequestPlan",
    "CreateCheckoutBillingResponse",
    "CreatePortalBillingResponse",
    "CreatePortalWebhooksResponse",
    "CreatePrivacyRequestKind",
    "CreateTrunkInputBaseline",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "DiscoverContextsRequestChannel",
    "DiscoverContextsResponse",
    "DiscoveryResult",
    "DiscoveryResultChannel",
    "EditContextInputChangesItem",
    "EditContextInputChangesItemDelete",
    "EditContextInputChangesItemPut",
    "EditContextInputChangesItem_Delete",
    "EditContextInputChangesItem_Put",
    "EditContextsResponse",
    "Error",
    "ErrorError",
    "FileInput",
    "FileRecord",
    "ForbiddenError",
    "GetBillingResponse",
    "GetBillingResponsePlan",
    "GetRollbackPlanContextsResponse",
    "HistoryContextsResponse",
    "InspectContextsResponse",
    "ListReleasesRequestStatus",
    "ListReleasesResponse",
    "ListScopesResponse",
    "ListWebhooksResponse",
    "ListWebhooksResponseDataItem",
    "ListWebhooksResponseDataItemStatus",
    "ListWorkspacesResponse",
    "NotFoundError",
    "PromotionRequest",
    "PromotionRequestChangesItem",
    "PromotionRequestStatus",
    "PublishContextsResponse",
    "Revision",
    "Scope",
    "ScopeEnvironmentsItem",
    "ScopeEnvironmentsItemName",
    "ServiceUnavailableError",
    "SetSpendLimitBillingResponse",
    "Trunk",
    "TrunkBranches",
    "__version__",
    "billing",
    "context_sets",
    "contexts",
    "health",
    "privacy",
    "releases",
    "scopes",
    "webhooks",
    "workspaces",
]
