// Generated by scripts/generate-examples.mjs; reviewed inputs are beside this file.
import {run} from '../shared.mjs';
export const execute = (client,input) => client.contexts.export(input["trunkId"], input["contextKey"], input["request"]);
await run(import.meta.url, 'contexts.export', execute);
