# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawBillingClient, RawBillingClient
from .types.create_checkout_billing_request_plan import CreateCheckoutBillingRequestPlan
from .types.create_checkout_billing_response import CreateCheckoutBillingResponse
from .types.create_portal_billing_response import CreatePortalBillingResponse
from .types.get_billing_response import GetBillingResponse
from .types.set_spend_limit_billing_response import SetSpendLimitBillingResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetBillingResponse:
        """
        Organization subscription and usage summary. Requires billing:read. MCP metering is currently inactive.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBillingResponse
            Current plan, subscription status, allowance, usage, cap in cents, and canManage capability.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.billing.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def create_checkout(
        self, *, plan: CreateCheckoutBillingRequestPlan, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateCheckoutBillingResponse:
        """
        Requires billing:manage. Reuses an unexpired checkout; existing subscriptions must use the portal. Body limited to 4096 bytes.

        Parameters
        ----------
        plan : CreateCheckoutBillingRequestPlan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCheckoutBillingResponse
            Object with url for the hosted Stripe checkout.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.billing.create_checkout(
            plan="starter",
        )
        """
        _response = self._raw_client.create_checkout(plan=plan, request_options=request_options)
        return _response.data

    def create_portal(self, *, request_options: typing.Optional[RequestOptions] = None) -> CreatePortalBillingResponse:
        """
        Requires billing:manage and an existing organization customer.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalBillingResponse
            Object with url for the hosted Stripe billing portal.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.billing.create_portal()
        """
        _response = self._raw_client.create_portal(request_options=request_options)
        return _response.data

    def set_spend_limit(
        self, *, cents: int, request_options: typing.Optional[RequestOptions] = None
    ) -> SetSpendLimitBillingResponse:
        """
        Requires billing:manage. Audited organization overage cap; excludes subscription fees and taxes. Does not activate metering.

        Parameters
        ----------
        cents : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetSpendLimitBillingResponse
            Object with the saved spendLimitCents.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.billing.set_spend_limit(
            cents=1,
        )
        """
        _response = self._raw_client.set_spend_limit(cents=cents, request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetBillingResponse:
        """
        Organization subscription and usage summary. Requires billing:read. MCP metering is currently inactive.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBillingResponse
            Current plan, subscription status, allowance, usage, cap in cents, and canManage capability.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.billing.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def create_checkout(
        self, *, plan: CreateCheckoutBillingRequestPlan, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateCheckoutBillingResponse:
        """
        Requires billing:manage. Reuses an unexpired checkout; existing subscriptions must use the portal. Body limited to 4096 bytes.

        Parameters
        ----------
        plan : CreateCheckoutBillingRequestPlan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCheckoutBillingResponse
            Object with url for the hosted Stripe checkout.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.billing.create_checkout(
                plan="starter",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_checkout(plan=plan, request_options=request_options)
        return _response.data

    async def create_portal(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalBillingResponse:
        """
        Requires billing:manage and an existing organization customer.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalBillingResponse
            Object with url for the hosted Stripe billing portal.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.billing.create_portal()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_portal(request_options=request_options)
        return _response.data

    async def set_spend_limit(
        self, *, cents: int, request_options: typing.Optional[RequestOptions] = None
    ) -> SetSpendLimitBillingResponse:
        """
        Requires billing:manage. Audited organization overage cap; excludes subscription fees and taxes. Does not activate metering.

        Parameters
        ----------
        cents : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetSpendLimitBillingResponse
            Object with the saved spendLimitCents.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.billing.set_spend_limit(
                cents=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_spend_limit(cents=cents, request_options=request_options)
        return _response.data
