# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.trunk import Trunk
from .raw_client import AsyncRawWorkspacesClient, RawWorkspacesClient
from .types.create_trunk_input_baseline import CreateTrunkInputBaseline
from .types.list_workspaces_response import ListWorkspacesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkspacesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkspacesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWorkspacesResponse:
        """
        Parameters
        ----------
        cursor : typing.Optional[str]

        q : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWorkspacesResponse
            Trunks readable by the principal in the active organization. Name/slug search runs before pagination. Pass nextCursor as cursor with unchanged filters until null. Cursors pin principal-bound candidate snapshots for 15 minutes; authorization is rechecked on every page. Snapshot limits are 10000 records and 8 MB; narrow oversized queries.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.workspaces.list()
        """
        _response = self._raw_client.list(cursor=cursor, q=q, limit=limit, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        baseline: typing.Optional[CreateTrunkInputBaseline] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Trunk:
        """
        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        baseline : typing.Optional[CreateTrunkInputBaseline]
            Copy one authorized immutable context revision into the new workspace's staging environment. Copies verified files and current display metadata, not history, notes, permissions or production releases. The workspace name is reserved for this exact baseline; retry with identical inputs after a partial failure. Destination storage allowances apply. This is a snapshot copy, not a full Git repository fork.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trunk
            Organization-owned trunk with a default FGA scope and staging and production environments.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.workspaces.create(
            name="name",
        )
        """
        _response = self._raw_client.create(
            name=name, description=description, baseline=baseline, request_options=request_options
        )
        return _response.data

    def get(self, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Trunk:
        """
        Parameters
        ----------
        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trunk
            Authorized workspace metadata

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.workspaces.get(
            trunk_id="trunkId",
        )
        """
        _response = self._raw_client.get(trunk_id, request_options=request_options)
        return _response.data

    def audit(
        self,
        trunk_id: str,
        *,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        trunk_id : str

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Authorized trunk audit events.

        Examples
        --------
        from agenttrunk import AgentTrunk

        client = AgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )
        client.workspaces.audit(
            trunk_id="trunkId",
        )
        """
        _response = self._raw_client.audit(trunk_id, limit=limit, request_options=request_options)
        return _response.data


class AsyncWorkspacesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkspacesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkspacesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkspacesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWorkspacesResponse:
        """
        Parameters
        ----------
        cursor : typing.Optional[str]

        q : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWorkspacesResponse
            Trunks readable by the principal in the active organization. Name/slug search runs before pagination. Pass nextCursor as cursor with unchanged filters until null. Cursors pin principal-bound candidate snapshots for 15 minutes; authorization is rechecked on every page. Snapshot limits are 10000 records and 8 MB; narrow oversized queries.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(cursor=cursor, q=q, limit=limit, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        baseline: typing.Optional[CreateTrunkInputBaseline] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Trunk:
        """
        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        baseline : typing.Optional[CreateTrunkInputBaseline]
            Copy one authorized immutable context revision into the new workspace's staging environment. Copies verified files and current display metadata, not history, notes, permissions or production releases. The workspace name is reserved for this exact baseline; retry with identical inputs after a partial failure. Destination storage allowances apply. This is a snapshot copy, not a full Git repository fork.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trunk
            Organization-owned trunk with a default FGA scope and staging and production environments.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name, description=description, baseline=baseline, request_options=request_options
        )
        return _response.data

    async def get(self, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Trunk:
        """
        Parameters
        ----------
        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Trunk
            Authorized workspace metadata

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.get(
                trunk_id="trunkId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(trunk_id, request_options=request_options)
        return _response.data

    async def audit(
        self,
        trunk_id: str,
        *,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        trunk_id : str

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Authorized trunk audit events.

        Examples
        --------
        import asyncio

        from agenttrunk import AsyncAgentTrunk

        client = AsyncAgentTrunk(
            access_token="YOUR_ACCESS_TOKEN",
        )


        async def main() -> None:
            await client.workspaces.audit(
                trunk_id="trunkId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.audit(trunk_id, limit=limit, request_options=request_options)
        return _response.data
