// This file was auto-generated by Fern from our API Definition.

import * as AgentTrunkApi from "../../src/api/index";
import { AgentTrunkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContextsClient", () => {
    test("export (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/export")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.export("trunkId", "contextKey", {
            revisionId: "revisionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("export (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/export")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.export("trunkId", "contextKey", {
                revisionId: "revisionId",
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("export (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/export")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.export("trunkId", "contextKey", {
                revisionId: "revisionId",
            });
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("getRollbackPlan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            eligible: true,
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "reason",
        };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.getRollbackPlan("trunkId", "contextKey", {
            revisionId: "revisionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getRollbackPlan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.getRollbackPlan("trunkId", "contextKey", {
                revisionId: "revisionId",
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("getRollbackPlan (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.getRollbackPlan("trunkId", "contextKey", {
                revisionId: "revisionId",
            });
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("getRollbackPlan (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.getRollbackPlan("trunkId", "contextKey", {
                revisionId: "revisionId",
            });
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("stageRollback (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            revisionId: "revisionId",
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "reason",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.stageRollback("trunkId", "contextKey", {
            revisionId: "revisionId",
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "reason",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("stageRollback (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            revisionId: "revisionId",
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "x",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.stageRollback("trunkId", "contextKey", {
                revisionId: "revisionId",
                expectedStagingRevisionId: "expectedStagingRevisionId",
                reason: "x",
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("stageRollback (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            revisionId: "revisionId",
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "x",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.stageRollback("trunkId", "contextKey", {
                revisionId: "revisionId",
                expectedStagingRevisionId: "expectedStagingRevisionId",
                reason: "x",
            });
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("stageRollback (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            revisionId: "revisionId",
            expectedStagingRevisionId: "expectedStagingRevisionId",
            reason: "x",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/contexts/contextKey/rollback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.stageRollback("trunkId", "contextKey", {
                revisionId: "revisionId",
                expectedStagingRevisionId: "expectedStagingRevisionId",
                reason: "x",
            });
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("publish (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            contextKey: "contextKey",
            title: "title",
            kind: "skill",
            files: [{ path: "path", contentBase64: "contentBase64" }],
        };
        const rawResponseBody = {
            context: {
                id: "id",
                trunkId: "trunkId",
                scopeId: "scopeId",
                key: "key",
                title: "title",
                kind: "skill",
                summary: "summary",
                tags: ["tags"],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            revision: {
                id: "id",
                contextId: "contextId",
                packageDigest: "packageDigest",
                parentRevisionId: "parentRevisionId",
                files: [{ path: "path", size: 1, sha256: "sha256" }],
                createdAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/publications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.publish("trunkId", {
            contextKey: "contextKey",
            title: "title",
            kind: "skill",
            files: [
                {
                    path: "path",
                    contentBase64: "contentBase64",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("publish (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            contextKey: "contextKey",
            title: "title",
            kind: "skill",
            files: [
                { path: "x", contentBase64: "contentBase64" },
                { path: "x", contentBase64: "contentBase64" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/publications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.publish("trunkId", {
                contextKey: "contextKey",
                title: "title",
                kind: "skill",
                files: [
                    {
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                    {
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                ],
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("publish (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            contextKey: "contextKey",
            title: "title",
            kind: "skill",
            files: [
                { path: "x", contentBase64: "contentBase64" },
                { path: "x", contentBase64: "contentBase64" },
            ],
        };
        const rawResponseBody = { error: { code: "code", message: "message", requestId: "requestId" } };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/publications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.publish("trunkId", {
                contextKey: "contextKey",
                title: "title",
                kind: "skill",
                files: [
                    {
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                    {
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                ],
            });
        }).rejects.toThrow(AgentTrunkApi.ContentTooLargeError);
    });

    test("share", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/contexts/contextKey/share")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.share("trunkId", "contextKey");
        expect(response).toEqual(rawResponseBody);
    });

    test("discover", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    trunkId: "trunkId",
                    scopeId: "scopeId",
                    contextKey: "contextKey",
                    title: "title",
                    kind: "skill",
                    summary: "summary",
                    tags: ["tags"],
                    revisionId: "revisionId",
                    packageDigest: "packageDigest",
                    channel: "production",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            nextCursor: "nextCursor",
        };

        server.mockEndpoint().get("/v1/contexts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contexts.discover();
        expect(response).toEqual(rawResponseBody);
    });

    test("inspect (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            context: {
                id: "id",
                trunkId: "trunkId",
                scopeId: "scopeId",
                key: "key",
                title: "title",
                kind: "skill",
                summary: "summary",
                tags: ["tags"],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            revision: {
                id: "id",
                contextId: "contextId",
                packageDigest: "packageDigest",
                parentRevisionId: "parentRevisionId",
                files: [{ path: "path", size: 1, sha256: "sha256" }],
                createdAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.inspect("trunkId", "contextKey");
        expect(response).toEqual(rawResponseBody);
    });

    test("inspect (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.inspect("trunkId", "contextKey");
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("edit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            expectedRevisionId: "expectedRevisionId",
            changes: [{ operation: "put", path: "path", contentBase64: "contentBase64" }],
        };
        const rawResponseBody = {
            context: {
                id: "id",
                trunkId: "trunkId",
                scopeId: "scopeId",
                key: "key",
                title: "title",
                kind: "skill",
                summary: "summary",
                tags: ["tags"],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            revision: {
                id: "id",
                contextId: "contextId",
                packageDigest: "packageDigest",
                parentRevisionId: "parentRevisionId",
                files: [{ path: "path", size: 1, sha256: "sha256" }],
                createdAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/trunks/trunkId/contexts/contextKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.edit("trunkId", "contextKey", {
            expectedRevisionId: "expectedRevisionId",
            changes: [
                {
                    operation: "put",
                    path: "path",
                    contentBase64: "contentBase64",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("edit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            expectedRevisionId: "expectedRevisionId",
            changes: [
                { operation: "put", path: "x", contentBase64: "contentBase64" },
                { operation: "put", path: "x", contentBase64: "contentBase64" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/trunks/trunkId/contexts/contextKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.edit("trunkId", "contextKey", {
                expectedRevisionId: "expectedRevisionId",
                changes: [
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                ],
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("edit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            expectedRevisionId: "expectedRevisionId",
            changes: [
                { operation: "put", path: "x", contentBase64: "contentBase64" },
                { operation: "put", path: "x", contentBase64: "contentBase64" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/trunks/trunkId/contexts/contextKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.edit("trunkId", "contextKey", {
                expectedRevisionId: "expectedRevisionId",
                changes: [
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                ],
            });
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("edit (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = {
            expectedRevisionId: "expectedRevisionId",
            changes: [
                { operation: "put", path: "x", contentBase64: "contentBase64" },
                { operation: "put", path: "x", contentBase64: "contentBase64" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/trunks/trunkId/contexts/contextKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.edit("trunkId", "contextKey", {
                expectedRevisionId: "expectedRevisionId",
                changes: [
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                    {
                        operation: "put",
                        path: "x",
                        contentBase64: "contentBase64",
                    },
                ],
            });
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("history (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    contextId: "contextId",
                    packageDigest: "packageDigest",
                    parentRevisionId: "parentRevisionId",
                    files: [{ path: "path", size: 1, sha256: "sha256" }],
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
            next: "next",
        };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/history")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.history("trunkId", "contextKey");
        expect(response).toEqual(rawResponseBody);
    });

    test("history (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/history")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.history("trunkId", "contextKey");
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("compare (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/compare")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.compare("trunkId", "contextKey");
        expect(response).toEqual(rawResponseBody);
    });

    test("compare (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/compare")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.compare("trunkId", "contextKey");
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("compare (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/compare")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.compare("trunkId", "contextKey");
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("getProvenance (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.getProvenance("trunkId", "contextKey");
        expect(response).toEqual(rawResponseBody);
    });

    test("getProvenance (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.getProvenance("trunkId", "contextKey");
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("putProvenance (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "text" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contexts.putProvenance("trunkId", "contextKey", {
            revisionId: "revisionId",
            text: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("putProvenance (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "x", expectedNotesCommitSha: null };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.putProvenance("trunkId", "contextKey", {
                revisionId: "revisionId",
                text: "x",
                expectedNotesCommitSha: null,
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("putProvenance (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "x", expectedNotesCommitSha: null };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.putProvenance("trunkId", "contextKey", {
                revisionId: "revisionId",
                text: "x",
                expectedNotesCommitSha: null,
            });
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("putProvenance (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "x", expectedNotesCommitSha: null };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.putProvenance("trunkId", "contextKey", {
                revisionId: "revisionId",
                text: "x",
                expectedNotesCommitSha: null,
            });
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("putProvenance (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "x", expectedNotesCommitSha: null };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.putProvenance("trunkId", "contextKey", {
                revisionId: "revisionId",
                text: "x",
                expectedNotesCommitSha: null,
            });
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("putProvenance (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { revisionId: "revisionId", text: "x", expectedNotesCommitSha: null };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/trunks/trunkId/contexts/contextKey/provenance")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contexts.putProvenance("trunkId", "contextKey", {
                revisionId: "revisionId",
                text: "x",
                expectedNotesCommitSha: null,
            });
        }).rejects.toThrow(AgentTrunkApi.BadGatewayError);
    });
});
