// This file was auto-generated by Fern from our API Definition.

import { AgentTrunkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HealthClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/healthz").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.get();
        expect(response).toEqual(rawResponseBody);
    });
});
