// This file was auto-generated by Fern from our API Definition.

import * as AgentTrunkApi from "../../src/api/index";
import { AgentTrunkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PrivacyClient", () => {
    test("assignReview (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests/requestId/review")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privacy.assignReview("trunkId", "requestId", {
            key: "value",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("assignReview (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests/requestId/review")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.assignReview("trunkId", "requestId", {
                string: {
                    key: "value",
                },
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("assignReview (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests/requestId/review")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.assignReview("trunkId", "requestId", {
                string: {
                    key: "value",
                },
            });
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("assignReview (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests/requestId/review")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.assignReview("trunkId", "requestId", {
                string: {
                    key: "value",
                },
            });
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("erasurePlan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/erasure-plan")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privacy.erasurePlan("trunkId");
        expect(response).toEqual(rawResponseBody);
    });

    test("erasurePlan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/erasure-plan")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.erasurePlan("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/privacy-requests")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privacy.list("trunkId");
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/privacy-requests")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.list("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "access" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.privacy.create("trunkId", {
            kind: "access",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "access" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.create("trunkId", {
                kind: "access",
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "access" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/privacy-requests")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.privacy.create("trunkId", {
                kind: "access",
            });
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });
});
