// This file was auto-generated by Fern from our API Definition.

import * as AgentTrunkApi from "../../src/api/index";
import { AgentTrunkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            nextCursor: "nextCursor",
            data: [
                {
                    sequence: "sequence",
                    eventId: "eventId",
                    status: "pending",
                    attempts: 1,
                    lastError: "lastError",
                    svixMessageId: "svixMessageId",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/webhooks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.list("trunkId");
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/webhooks")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.list("trunkId");
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/webhooks")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.list("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/webhooks")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.list("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ServiceUnavailableError);
    });

    test("createPortal (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/portal")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.createPortal("trunkId");
        expect(response).toEqual(rawResponseBody);
    });

    test("createPortal (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/portal")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.createPortal("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("createPortal (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/portal")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.createPortal("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("createPortal (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/portal")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.createPortal("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ServiceUnavailableError);
    });

    test("retry (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/eventId/retry")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.retry("trunkId", "eventId");
        expect(response).toEqual(rawResponseBody);
    });

    test("retry (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/eventId/retry")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.retry("trunkId", "eventId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("retry (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/eventId/retry")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.retry("trunkId", "eventId");
        }).rejects.toThrow(AgentTrunkApi.ConflictError);
    });

    test("retry (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks/trunkId/webhooks/eventId/retry")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.retry("trunkId", "eventId");
        }).rejects.toThrow(AgentTrunkApi.ServiceUnavailableError);
    });
});
