// This file was auto-generated by Fern from our API Definition.

import * as AgentTrunkApi from "../../src/api/index";
import { AgentTrunkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WorkspacesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            nextCursor: "nextCursor",
            data: [
                {
                    id: "id",
                    organizationId: "organizationId",
                    name: "name",
                    slug: "slug",
                    createdBy: "createdBy",
                    branches: { staging: null, production: null },
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/v1/trunks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.workspaces.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "id",
            organizationId: "organizationId",
            name: "name",
            slug: "slug",
            createdBy: "createdBy",
            branches: { staging: "staging", production: "production" },
            createdAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/trunks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspaces.create({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/trunks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workspaces.create({
                name: "x",
            });
        }).rejects.toThrow(AgentTrunkApi.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            organizationId: "organizationId",
            name: "name",
            slug: "slug",
            createdBy: "createdBy",
            branches: { staging: "staging", production: "production" },
            createdAt: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/v1/trunks/trunkId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.workspaces.get("trunkId");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/trunks/trunkId").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.workspaces.get("trunkId");
        }).rejects.toThrow(AgentTrunkApi.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/trunks/trunkId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.workspaces.get("trunkId");
        }).rejects.toThrow(AgentTrunkApi.NotFoundError);
    });

    test("audit", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentTrunkClient({ maxRetries: 0, accessToken: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/trunks/trunkId/audit")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workspaces.audit("trunkId");
        expect(response).toEqual(rawResponseBody);
    });
});
